---
title: "O2lib p<0.05"
author: "Nina Boskovic"
date: "2024-07-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

fluctuated_data<-read.delim("fluctuated_data.txt", header= TRUE, check.names = FALSE)
metadata<- read.table("metadata.txt")
fluctuated_data <- fluctuated_data[, -41]
metadata<- metadata[-41,]
```

```{r, message=FALSE}
library(Seurat)
library(SeuratObject)
library(ggplot2)
```

```{r}
strt.seurat.obj <- CreateSeuratObject(counts = fluctuated_data, project = "STRT", min.cells = 10, min.features = 2000 )
strt.seurat.obj@meta.data <- metadata

```

```{r, message=FALSE}
strt.seurat.obj<- NormalizeData(strt.seurat.obj, normalization.method = "LogNormalize", scale.factor = 10000)
reads.p1<- fluctuated_data + 1 
reads.p1.spikes<- colSums(reads.p1[1:78, ])
strt.seurat.obj[["RNA"]]@data <- as(as.matrix(log(reads.p1/rep(reads.p1.spikes, each=nrow(reads.p1)))), "dgCMatrix")
all.genes <- row.names(strt.seurat.obj)
strt.seurat.obj <- ScaleData(strt.seurat.obj, features = all.genes)

```

```{r}
strt.seurat.obj <- RunPCA(strt.seurat.obj, features = all.genes, npcs = 33) 

pcaresults<- VizDimLoadings(strt.seurat.obj, dims = 1:2, reduction = "pca")


c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

desired_order<- c("oocyte", "Zygote", "4cell", "8cell", "16cell", "blastocyst")
strt.seurat.obj$Developmental_stages<- factor(strt.seurat.obj$Developmental_stages, levels = desired_order)

pcaplot<-DimPlot(strt.seurat.obj, reduction = "pca", cols = c25, group.by = "Developmental_stages", shape.by = "Condition", label = T, label.size = 4, pt.size=3)+
  ggtitle("2nd library")

ggsave(pcaplot, filename= "pcaplotallsamples.pdf", width = 10, height = 10)

strt.seurat.obj <- RunUMAP(strt.seurat.obj, dims = 1:15, verbose = F)
umaptplot<- DimPlot(strt.seurat.obj,label.size = 4, cols = c25, group.by = "Developmental_stages", shape.by = "Condition", repel = T, label = T, pt.size = 4) +
  ggtitle("2nd library")
```

```{r}
library(DESeq2)
library(ggrepel)
dds <- DESeqDataSetFromMatrix(countData = fluctuated_data, 
                              colData = metadata, 
                              design = ~ Stage)
dds <- estimateSizeFactors(dds, controlGenes=1:77) #spike ins in the original dataset


keep <- rowSums(counts(dds)) >= 10
dds <- dds[keep,]
levels(dds$Stage)
dds1 <- DESeq(dds)
```



```{r}

hypoxia_8c_vs_zygote <- as.data.frame(results(dds1, contrast=c("Stage", "8cHO", "zHO")))
hypoxia_16c_vs_zygote <- as.data.frame(results(dds1, contrast=c("Stage", "16cHO", "zHO")))
hypoxia_blas_vs_zygote <- as.data.frame(results(dds1, contrast=c("Stage", "bHO", "zHO")))
hypoxia_blas_vs_16c <- as.data.frame(results(dds1, contrast=c("Stage", "bHO", "16cHO")))


#removing the NA * The genes with NA are the ones DESeq2 has filtered out *

hypoxia_8c_vs_zygote <- subset(hypoxia_8c_vs_zygote, !is.na(padj) )
hypoxia_16c_vs_zygote <- subset(hypoxia_16c_vs_zygote, !is.na(padj) )
hypoxia_blas_vs_zygote<- subset(hypoxia_blas_vs_zygote, !is.na(padj))
hypoxia_blas_vs_16c <- subset(hypoxia_blas_vs_16c, !is.na(padj))

hypoxia_8c_vs_zygotevol0.05 <- hypoxia_8c_vs_zygote%>% mutate(gene_type = case_when( log2FoldChange <= -1 & padj < 0.05 ~ "down", log2FoldChange >= 1 & padj < 0.05 ~ "up", TRUE ~ "ns"))

hypoxia_8c_vs_zygotevol0.05$Symbol<- rownames(hypoxia_8c_vs_zygotevol0.05) 

UP8c_zygotehyp0.05 <- hypoxia_8c_vs_zygotevol0.05[hypoxia_8c_vs_zygotevol0.05$gene_type %in% "up",]
DOWN8c_zygotehyp0.05 <- hypoxia_8c_vs_zygotevol0.05[hypoxia_8c_vs_zygotevol0.05$gene_type %in% "down",]
TOT8c_zygotehyp0.05 <- rbind(UP8c_zygotehyp0.05, DOWN8c_zygotehyp0.05)
TOT8c_zygotehyp0.05$Symbol<- rownames(TOT8c_zygotehyp0.05)

cols <- c("down" = "#A67F7B", "up" = "#7B9FA6", "ns" = "grey")
sizes <- c("up" = 4, "down" = 4, "ns" = 2)
alphas <- c("up" = 2, "down" = 2, "ns" = 0.5) 


hypoxia_8c_vs_zygotevolano0.05 <- ggplot(data = hypoxia_8c_vs_zygotevol0.05, aes(x=log2FoldChange, y=-log10(padj))
) + geom_point (aes(fill = gene_type), shape = 21, size = 2, color = "black"
) + geom_point(data = UP8c_zygotehyp0.05 , shape = 21, size = 4, fill = "#7fbf7b", colour = "black"
) + geom_point(data = DOWN8c_zygotehyp0.05, shape = 21, size = 4, fill = "#af8dc3", colour = "black"
) + geom_label_repel(data = TOT8c_zygotehyp0.05, aes(label = Symbol), force = 2,nudge_y = 1,
) + scale_fill_manual(values = cols) + scale_alpha_manual(values = alphas
) + theme_bw() +
  xlab("Expression change (log2FoldChange)")+
  ylab("Significance (-log10(padj))")+
  ggtitle(" Comparison of 8cell stage and zygote stage (hypoxia, 2nd library) ")+ 
  xlim(-8, 8) +
  ylim(0, 50)

ggsave(hypoxia_8c_vs_zygotevolano0.05, filename= "hypoxia_8c_vs_zygot(padj<0.05).pdf", width = 10, height = 10)

write.table(DOWN8c_zygotehyp0.05, file = "DOWN8c_zygotehyp0.05.txt", sep = "\t", row.names = T, col.names = TRUE)

#16c vs zygote hypoxia

hypoxia_16c_vs_zygotevol0.05 <- hypoxia_16c_vs_zygote %>% mutate(gene_type = case_when(log2FoldChange <= -1 & padj < 0.05 ~ "down", log2FoldChange >= 1 & padj < 0.05 ~ "up", TRUE ~ "ns"))
hypoxia_16c_vs_zygotevol0.05$Symbol<- rownames(hypoxia_16c_vs_zygotevol0.05) 


UP16c_zygotehyp0.05 <- hypoxia_16c_vs_zygotevol0.05[hypoxia_16c_vs_zygotevol0.05$gene_type %in% "up",]
DOWN16c_zygotehyp0.05 <- hypoxia_16c_vs_zygotevol0.05[hypoxia_16c_vs_zygotevol0.05$gene_type %in% "down",]
TOT16c_zygotehyp0.05 <- rbind(UP16c_zygotehyp0.05, DOWN16c_zygotehyp0.05)
TOT16c_zygotehyp0.05$Symbol<- rownames(TOT16c_zygotehyp0.05)


hypoxia_16c_vs_zygotevolano0.05 <- ggplot(data = hypoxia_16c_vs_zygotevol0.05, aes(x=log2FoldChange, y=-log10(padj))
) + geom_point (aes(fill = gene_type), shape = 21, size = 2, color = "black"
) + geom_point(data = UP16c_zygotehyp0.05 , shape = 21, size = 4, fill = "#7fbf7b", colour = "black"
) + geom_point(data = DOWN16c_zygotehyp0.05, shape = 21, size = 4, fill = "#af8dc3", colour = "black"
) + geom_label_repel(data = TOT16c_zygotehyp0.05, aes(label = Symbol), force = 2,nudge_y = 1,
) + scale_fill_manual(values = cols) + scale_alpha_manual(values = alphas
) + theme_bw() +
  xlab("Expression change (log2FoldChange)")+
  ylab("Significance (-log10(padj))")+
  ggtitle(" Comparison of 16cell stage and zygote stage (hypoxia, 2nd library)") + 
  xlim(-8, 8) +
  ylim(0, 50)

ggsave(hypoxia_16c_vs_zygotevolano0.05 , filename= "hypoxia_16c_vs_zygot(padj<0.05).pdf", width = 10, height = 10)
write.table(DOWN16c_zygotehyp0.05, file = "DOWN16c_zygotehyp0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(UP16c_zygotehyp0.05, file = "UP16c_zygotehyp0.05.txt", sep = "\t", row.names = T, col.names = TRUE)

#volcano plot blastocyst vs zygote

hypoxia_blast_vs_zygotevol0.05 <- hypoxia_blas_vs_zygote%>% mutate(gene_type = case_when(log2FoldChange <= -1 & padj < 0.05 ~ "down", log2FoldChange >= 1 & padj < 0.05 ~ "up", TRUE ~ "ns"))
hypoxia_blast_vs_zygotevol0.05$Symbol<- rownames(hypoxia_blast_vs_zygotevol0.05) 

UPbast_zygotehyp0.05 <- hypoxia_blast_vs_zygotevol0.05[hypoxia_blast_vs_zygotevol0.05$gene_type %in% "up",]
DOWNblast_zygotehyp0.05 <- hypoxia_blast_vs_zygotevol0.05[hypoxia_blast_vs_zygotevol0.05$gene_type %in% "down",]
TOTblast_zygotehyp0.05 <- rbind(UPbast_zygotehyp0.05, DOWNblast_zygotehyp0.05)
TOTblast_zygotehyp0.05$Symbol<- rownames(TOTblast_zygotehyp0.05)

hypoxia_blast_vs_zygotevolano0.05 <- ggplot(data = hypoxia_blast_vs_zygotevol0.05, aes(x=log2FoldChange, y=-log10(padj))
) + geom_point (aes(fill = gene_type), shape = 21, size = 2, color = "black"
) + geom_point(data = UPbast_zygotehyp0.05 , shape = 21, size = 4, fill = "#7fbf7b", colour = "black"
) + geom_point(data = DOWNblast_zygotehyp0.05, shape = 21, size = 4, fill = "#af8dc3", colour = "black"
) + geom_label_repel(data = TOTblast_zygotehyp0.05, aes(label = Symbol), force = 2,nudge_y = 1,
) + scale_fill_manual(values = cols) + scale_alpha_manual(values = alphas
) + theme_bw() +
  xlab("Expression change (log2FoldChange)")+
  ylab("Significance (-log10(padj))")+
  ggtitle(" Comparison of blastocyst stage and zygote stage (hypoxia, 2nd library) ")+ 
  xlim(-8, 8) +
  ylim(0, 50)

ggsave(hypoxia_blast_vs_zygotevolano0.05, filename= "hypoxia_blastocyst_vs_zygot(padj<0.05).pdf", width = 10, height = 10)
write.table(DOWNblast_zygotehyp0.05, file = "DOWNblast_zygotehyp0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(UPbast_zygotehyp0.05, file = "UPbast_zygotehyp0.05.txt", sep = "\t", row.names = T, col.names = TRUE)

#volcano plot blastocyst vs 16C ho

hypoxia_blast_vs_16cvol0.05 <- hypoxia_blas_vs_16c%>% mutate(gene_type = case_when(log2FoldChange <= -1 & padj < 0.05 ~ "down", log2FoldChange >= 1 & padj < 0.05 ~ "up", TRUE ~ "ns"))
hypoxia_blast_vs_16cvol0.05$Symbol<- rownames(hypoxia_blast_vs_16cvol0.05) 

UPbast_16chyp0.05 <- hypoxia_blast_vs_16cvol0.05[hypoxia_blast_vs_16cvol0.05$gene_type %in% "up",]
DOWNblast_16chyp0.05 <- hypoxia_blast_vs_16cvol0.05[hypoxia_blast_vs_16cvol0.05$gene_type %in% "down",]
TOTblast_16chyp0.05 <- rbind(UPbast_16chyp0.05, DOWNblast_16chyp0.05)
TOTblast_16chyp0.05$Symbol<- rownames(TOTblast_16chyp0.05)

hypoxia_blast_vs_16cvolano0.05 <- ggplot(data = hypoxia_blast_vs_16cvol0.05, aes(x=log2FoldChange, y=-log10(padj))
) + geom_point (aes(fill = gene_type), shape = 21, size = 2, color = "black"
) + geom_point(data = UPbast_16chyp0.05 , shape = 21, size = 4, fill = "#7fbf7b", colour = "black"
) + geom_point(data = DOWNblast_16chyp0.05, shape = 21, size = 4, fill = "#af8dc3", colour = "black"
) + geom_label_repel(data = TOTblast_16chyp0.05, aes(label = Symbol), force = 2,nudge_y = 1,
) + scale_fill_manual(values = cols) + scale_alpha_manual(values = alphas
) + theme_bw() +
  xlab("Expression change (log2FoldChange)")+
  ylab("Significance (-log10(padj))")+
  ggtitle(" Comparison of blastocyst stage and 15c stage (hypoxia, 2nd library) ")+ 
  xlim(-8, 8) +
  ylim(0, 40)

ggsave(hypoxia_blast_vs_16cvolano0.05, filename= "hypoxia_blastocyst_vs_16c(padj<0.05).pdf", width = 10, height = 10)
write.table(DOWNblast_16chyp0.05, file = "DOWNblast_16chyp0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(UPbast_16chyp0.05, file = "UPbast_16chyp0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
```
#NORMOXIA

```{r}
normoxia_8c_vs_zygote <- as.data.frame(results(dds1, contrast=c("Stage", "8cNO", "zNO")))
normoxia_16c_vs_zygote <- as.data.frame(results(dds1, contrast=c("Stage", "16cNO", "zNO")))
normoxia_blas_vs_zygote <- as.data.frame(results(dds1, contrast=c("Stage", "bNO", "zNO")))
normoxia_blas_vs_16c <- as.data.frame(results(dds1, contrast=c("Stage", "bNO", "16cNO")))

#cleaning up the tables by removing samples that have padj NA and spikeins

normoxia_8c_vs_zygote <- subset(normoxia_8c_vs_zygote, !is.na(padj) )
normoxia_16c_vs_zygote <- subset(normoxia_16c_vs_zygote, !is.na(padj) )
normoxia_blas_vs_zygote<- subset(normoxia_blas_vs_zygote, !is.na(padj) )
normoxia_blas_vs_16c <- subset(normoxia_blas_vs_16c, !is.na(padj) )

# volcano plots for normoxia
#8c vs zygote

normoxia_8c_vs_zygotevol0.05 <- normoxia_8c_vs_zygote %>% mutate(gene_type = case_when(log2FoldChange <= -1 & padj < 0.05 ~ "down", log2FoldChange >= 1 & padj < 0.05 ~ "up", TRUE ~ "ns"))
normoxia_8c_vs_zygotevol0.05$Symbol<- rownames(normoxia_8c_vs_zygotevol0.05) 

UP8c_zygotenorm0.05 <- normoxia_8c_vs_zygotevol0.05[normoxia_8c_vs_zygotevol0.05$gene_type %in% "up",]
DOWN8c_zygotenorm0.05 <- normoxia_8c_vs_zygotevol0.05[normoxia_8c_vs_zygotevol0.05$gene_type %in% "down",]
TOT8c_zygotenorm0.05<- rbind(UP8c_zygotenorm0.05, DOWN8c_zygotenorm0.05)
TOT8c_zygotenorm0.05$Symbol<- rownames(TOT8c_zygotenorm0.05)


normoxia_8c_vs_zygotevolano0.05 <- ggplot(data = normoxia_8c_vs_zygotevol0.05, aes(x=log2FoldChange, y=-log10(padj))
) + geom_point (aes(fill = gene_type), shape = 21, size = 2, color = "black"
) + geom_point(data = UP8c_zygotenorm0.05 , shape = 21, size = 4, fill = "#7B9FA6", colour = "black"
) + geom_point(data = DOWN8c_zygotenorm0.05, shape = 21, size = 4, fill = "#A67F7B", colour = "black"
) + geom_label_repel(data = TOT8c_zygotenorm0.05, aes(label = Symbol), force = 2,nudge_y = 1,
) + scale_fill_manual(values = cols) + scale_alpha_manual(values = alphas
) + theme_bw() +
  xlab("Expression change (log2FoldChange)")+
  ylab("Significance (-log10(padj))")+
  ggtitle(" Comparison of 8cell stage and zygote stage (normoxia, 2nd library) ")+ 
  xlim(-8, 8) +
  ylim(0, 50)

ggsave(normoxia_8c_vs_zygotevolano0.05, filename= "normoxia_8c_vs_zygot(padj<0.05)lat.svg", width = 10, height = 10)
write.table(DOWN8c_zygotenorm0.05, file = "DOWN8c_zygotenorm0.05.txt", sep = "\t", row.names = T, col.names = TRUE)

#16c vs zygote

normoxia_16c_vs_zygotevol0.05 <- normoxia_16c_vs_zygote %>% mutate(gene_type = case_when(log2FoldChange <= -1 & padj < 0.05 ~ "down", log2FoldChange >= 1 & padj < 0.05 ~ "up", TRUE ~ "ns"))
normoxia_16c_vs_zygotevol0.05$Symbol<- rownames(normoxia_16c_vs_zygotevol0.05) 


UP16c_zygotenorm0.05 <- normoxia_16c_vs_zygotevol0.05[normoxia_16c_vs_zygotevol0.05$gene_type %in% "up",]
DOWN16c_zygotenorm0.05 <- normoxia_16c_vs_zygotevol0.05[normoxia_16c_vs_zygotevol0.05$gene_type %in% "down",]
TOT16c_zygotenorm0.05 <- rbind(UP16c_zygotenorm0.05, DOWN16c_zygotenorm0.05)
TOT16c_zygotenorm0.05$Symbol<- rownames(TOT16c_zygotenorm0.05)


normoxia_16c_vs_zygotevolano0.05 <- ggplot(data = normoxia_16c_vs_zygotevol0.05, aes(x=log2FoldChange, y=-log10(padj))
) + geom_point (aes(fill = gene_type), shape = 21, size = 2, color = "black"
) + geom_point(data = UP16c_zygotenorm0.05, shape = 21, size = 4, fill = "#7B9FA6", colour = "black"
) + geom_point(data = DOWN16c_zygotenorm0.05, shape = 21, size = 4, fill = "#A67F7B", colour = "black"
) + geom_label_repel(data = TOT16c_zygotenorm0.05, aes(label = Symbol), force = 2,nudge_y = 1,
) + scale_fill_manual(values = cols) + scale_alpha_manual(values = alphas
) + theme_bw() +
  xlab("Expression change (log2FoldChange)")+
  ylab("Significance (-log10(padj))")+
  ggtitle(" Comparison of 16cell stage and zygote stage(normoxia, 2nd library)")+ 
  xlim(-8, 8) +
  ylim(0, 50)
#7B9FA6
#8F9D88

"#7B9FA6"
"#A67F7B"

ggsave(normoxia_16c_vs_zygotevolano0.05, filename= "normoxia_16c_vs_zygotevolano(padj<0.05)lat.svg", width = 10, height = 10)

write.table(DOWN16c_zygotenorm0.05, file = "DOWN16c_zygotenorm0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(UP16c_zygotenorm0.05, file = "UP16c_zygotenorm0.05.txt", sep = "\t", row.names = T, col.names = TRUE)

# blastocyst vs zygote

normoxia_blas_vs_zygotevol0.05 <- normoxia_blas_vs_zygote%>% mutate(gene_type = case_when(log2FoldChange <= -1 & padj < 0.05 ~ "down", log2FoldChange >= 1 & padj < 0.05 ~ "up", TRUE ~ "ns"))
normoxia_blas_vs_zygotevol0.05$Symbol<- rownames(normoxia_blas_vs_zygotevol0.05) 

UPbast_zygotenorm0.05 <- normoxia_blas_vs_zygotevol0.05[normoxia_blas_vs_zygotevol0.05$gene_type %in% "up",]
DOWNblast_zygotenorm0.05 <- normoxia_blas_vs_zygotevol0.05[normoxia_blas_vs_zygotevol0.05$gene_type %in% "down",]
TOTblast_zygotenorm0.05 <- rbind(UPbast_zygotenorm0.05, DOWNblast_zygotenorm0.05)
TOTblast_zygotenorm0.05$Symbol<- rownames(TOTblast_zygotenorm0.05)

normoxia_blast_vs_zygotevolano0.05 <- ggplot(data = normoxia_blas_vs_zygotevol0.05, aes(x=log2FoldChange, y=-log10(padj))
) + geom_point (aes(fill = gene_type), shape = 21, size = 2, color = "black"
) + geom_point(data = UPbast_zygotenorm0.05 , shape = 21, size = 4, fill = "#7fbf7b", colour = "black"
) + geom_point(data = DOWNblast_zygotenorm0.05, shape = 21, size = 4, fill = "#af8dc3", colour = "black"
) + geom_label_repel(data = TOTblast_zygotenorm0.05, aes(label = Symbol), force = 2,nudge_y = 1,
) + scale_fill_manual(values = cols) + scale_alpha_manual(values = alphas
) + theme_bw() +
  xlab("Expression change (log2FoldChange)")+
  ylab("Significance (-log10(padj))")+
  ggtitle(" Comparison of blastocyst stage and zygote stage (normoxia, 2ns library) ")+ 
  xlim(-8, 8) +
  ylim(0, 50)

ggsave(normoxia_blast_vs_zygotevolano0.05, filename= "normoxia_blastocyst_vs_zygot(padj<0.05).pdf", width = 10, height = 10)
write.table(DOWNblast_zygotenorm0.05, file = "DOWNblast_zygotenorm0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(UPbast_zygotenorm0.05, file = "UPbast_zygotenorm0.05.txt", sep = "\t", row.names = T, col.names = TRUE)

#volcano plot blastocyst vs 16c

normoxia_blas_vs_16cvol0.05 <- normoxia_blas_vs_16c%>% mutate(gene_type = case_when(log2FoldChange <= -1 & padj < 0.05 ~ "down", log2FoldChange >= 1 & padj < 0.05 ~ "up", TRUE ~ "ns"))
normoxia_blas_vs_16cvol0.05$Symbol<- rownames(normoxia_blas_vs_16cvol0.05) 

UPbast_16cnorm0.05 <- normoxia_blas_vs_16cvol0.05[normoxia_blas_vs_16cvol0.05$gene_type %in% "up",]
DOWNblast_16cnorm0.05 <- normoxia_blas_vs_16cvol0.05[normoxia_blas_vs_16cvol0.05$gene_type %in% "down",]
TOTblast_16cnorm0.05 <- rbind(UPbast_16cnorm0.05, DOWNblast_16cnorm0.05)
TOTblast_16cnorm0.05$Symbol<- rownames(TOTblast_16cnorm0.05)

normoxia_blastocyst_vs_16cvolano0.05 <- ggplot(data = normoxia_blas_vs_16cvol0.05, aes(x=log2FoldChange, y=-log10(padj))
) + geom_point (aes(fill = gene_type), shape = 21, size = 2, color = "black"
) + geom_point(data = UPbast_16cnorm0.05 , shape = 21, size = 4, fill = "#7B9FA6", colour = "black"
) + geom_point(data = DOWNblast_16cnorm0.05, shape = 21, size = 4, fill = "#A67F7B", colour = "black"
) + geom_label_repel(data = TOTblast_16cnorm0.05, aes(label = Symbol), force = 2,nudge_y = 1,
) + scale_fill_manual(values = cols) + scale_alpha_manual(values = alphas
) + theme_bw() +
  ggtitle(" Comparison of blastocyst stage and 16cell stage, normoxia ")+ 
  labs( subtitle = "padj<0.01, LFC -1, 1")+
  xlim(-8, 8) +
  ylim(0, 40)

"#7B9FA6"
"#A67F7B"


ggsave(normoxia_blastocyst_vs_16cvolano0.05 , filename= "normoxia_blastocyst_vs_16cvolano(padj<0.05)lat.svg", width = 10, height = 10)
write.table(DOWNblast_16cnorm0.05, file = "DOWNblast_16cnorm0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(UPbast_16cnorm0.05, file = "UPbast_16cnorm0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
```
#ULTRAHYPOXIA

```{r}
ultrahypoxia_8c_vs_zygote <- as.data.frame(results(dds1, contrast=c("Stage", "8cUHO", "zUHO")))
ultrahypoxia_16c_vs_zygote <- as.data.frame(results(dds1, contrast=c("Stage", "16cUHO", "zUHO")))
ultrahypoxia_blas_vs_zygote <- as.data.frame(results(dds1, contrast=c("Stage", "bUHO", "zUHO")))
ultrahypoxia_blas_vs_16c <- as.data.frame(results(dds1, contrast=c("Stage", "bUHO", "16cUHO")))

#cleaning up the tables by removing samples that have padj NA and spikeins

ultrahypoxia_8c_vs_zygote <- subset(ultrahypoxia_8c_vs_zygote, !is.na(padj) )
ultrahypoxia_16c_vs_zygote <- subset(ultrahypoxia_16c_vs_zygote, !is.na(padj) )
ultrahypoxia_blas_vs_zygote<- subset(ultrahypoxia_blas_vs_zygote, !is.na(padj) )
ultrahypoxia_blas_vs_16c <- subset(ultrahypoxia_blas_vs_16c, !is.na(padj) )

#volcano plot 8c vs zygot

ultrahypoxia_8c_vs_zygotevol0.05 <- ultrahypoxia_8c_vs_zygote %>% mutate(gene_type = case_when(log2FoldChange <= -1 & padj < 0.05 ~ "down", log2FoldChange >= 1 & padj < 0.05 ~ "up", TRUE ~ "ns"))
ultrahypoxia_8c_vs_zygotevol0.05$Symbol<- rownames(ultrahypoxia_8c_vs_zygotevol0.05) 

UP8c_zygoteUHO0.05 <- ultrahypoxia_8c_vs_zygotevol0.05[ultrahypoxia_8c_vs_zygotevol0.05$gene_type %in% "up",]
DOWN8c_zygoteUHO0.05 <- ultrahypoxia_8c_vs_zygotevol0.05[ultrahypoxia_8c_vs_zygotevol0.05$gene_type %in% "down",]
TOT8c_zygoteUHO0.05 <- rbind(UP8c_zygoteUHO0.05, DOWN8c_zygoteUHO0.05)
TOT8c_zygoteUHO0.05$Symbol<- rownames(TOT8c_zygoteUHO0.05)


ultrahypoxia_8c_vs_zygotevolano0.05 <- ggplot(data = ultrahypoxia_8c_vs_zygotevol0.05, aes(x=log2FoldChange, y=-log10(padj))
) + geom_point (aes(fill = gene_type), shape = 21, size = 2, color = "black"
) + geom_point(data = UP8c_zygoteUHO0.05 , shape = 21, size = 4, fill = "#7fbf7b", colour = "black"
) + geom_point(data = DOWN8c_zygoteUHO0.05, shape = 21, size = 4, fill = "#af8dc3", colour = "black"
) + geom_label_repel(data = TOT8c_zygoteUHO0.05, aes(label = Symbol), force = 2,nudge_y = 1,
) + scale_fill_manual(values = cols) + scale_alpha_manual(values = alphas
) + theme_bw() +
  xlab("Expression change (log2FoldChange)")+
  ylab("Significance (-log10(padj))")+
  ggtitle(" Comparison of 8cell stage and zygote stage (ultrahypoxia, 2nd library) ")+ 
  xlim(-8, 8) +
  ylim(0, 50)


ggsave(ultrahypoxia_8c_vs_zygotevolano0.05, filename= "UHO_8c_vs_zygot(padj<0.05)1.pdf", width = 10, height = 10)
write.table(DOWN8c_zygoteUHO0.05, file = "DOWN8c_zygoteUHO0.05.txt", sep = "\t", row.names = T, col.names = TRUE)

#UHO 16c vs zygote

ultrahypoxia_16c_vs_zygotevol0.05 <- ultrahypoxia_16c_vs_zygote  %>% mutate(gene_type = case_when(log2FoldChange <= -1 & padj < 0.05 ~ "down", log2FoldChange >= 1 & padj < 0.05 ~ "up", TRUE ~ "ns"))
ultrahypoxia_16c_vs_zygotevol0.05$Symbol<- rownames(ultrahypoxia_16c_vs_zygotevol0.05) 


UP16c_zygoteUHO0.05 <- ultrahypoxia_16c_vs_zygotevol0.05[ultrahypoxia_16c_vs_zygotevol0.05$gene_type %in% "up",]
DOWN16c_zygoteUHO0.05 <- ultrahypoxia_16c_vs_zygotevol0.05[ultrahypoxia_16c_vs_zygotevol0.05$gene_type %in% "down",]
TOT16c_zygoteUHO0.05 <- rbind(UP16c_zygoteUHO0.05, DOWN16c_zygoteUHO0.05)
TOT16c_zygoteUHO0.05$Symbol<- rownames(TOT16c_zygoteUHO0.05)


ultrahypoxia_16c_vs_zygotevolano0.05 <- ggplot(data = ultrahypoxia_16c_vs_zygotevol0.05, aes(x=log2FoldChange, y=-log10(padj))
) + geom_point (aes(fill = gene_type), shape = 21, size = 2, color = "black"
) + geom_point(data = UP16c_zygoteUHO0.05 , shape = 21, size = 4, fill = "#7fbf7b", colour = "black"
) + geom_point(data = DOWN16c_zygoteUHO0.05, shape = 21, size = 4, fill = "#af8dc3", colour = "black"
) + geom_label_repel(data = TOT16c_zygoteUHO0.05, aes(label = Symbol), force = 2,nudge_y = 1,
) + scale_fill_manual(values = cols) + scale_alpha_manual(values = alphas
) + theme_bw() +
  xlab("Expression change (log2FoldChange)")+
  ylab("Significance (-log10(padj))")+
  ggtitle(" Comparison of 16cell stage and zygote stage (ultrahypoxia, 2nd library) ")+ 
  xlim(-8, 8) +
  ylim(0, 50)

ggsave(ultrahypoxia_16c_vs_zygotevolano0.05 , filename= "UHO_16c_vs_zygot(padj<0.05).pdf", width = 10, height = 10)
write.table(DOWN16c_zygoteUHO0.05, file = "DOWN16c_zygoteUHO0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(UP16c_zygoteUHO0.05, file = "UP16c_zygoteUHO0.05.txt", sep = "\t", row.names = T, col.names = TRUE)

# UHO blastocyst vs zygote

ultrahypoxia_blas_vs_zygotevol0.05 <- ultrahypoxia_blas_vs_zygote %>% mutate(gene_type = case_when(log2FoldChange <= -1 & padj < 0.05 ~ "down", log2FoldChange >= 1 & padj < 0.05 ~ "up", TRUE ~ "ns"))
ultrahypoxia_blas_vs_zygotevol0.05$Symbol<- rownames(ultrahypoxia_blas_vs_zygotevol0.05) 

UPbast_zygoteUHO0.05 <- ultrahypoxia_blas_vs_zygotevol0.05[ultrahypoxia_blas_vs_zygotevol0.05$gene_type %in% "up",]
DOWNblast_zygoteUHO0.05 <- ultrahypoxia_blas_vs_zygotevol0.05[ultrahypoxia_blas_vs_zygotevol0.05$gene_type %in% "down",]
TOTblast_zygoteUHO0.05 <- rbind(UPbast_zygoteUHO0.05, DOWNblast_zygoteUHO0.05)
TOTblast_zygoteUHO0.05$Symbol<- rownames(TOTblast_zygoteUHO0.05)

ultrahypoxia_blas_vs_zygotevolano0.05 <- ggplot(data = ultrahypoxia_blas_vs_zygotevol0.05, aes(x=log2FoldChange, y=-log10(padj))
) + geom_point (aes(fill = gene_type), shape = 21, size = 2, color = "black"
) + geom_point(data = UPbast_zygoteUHO0.05 , shape = 21, size = 4, fill = "#7fbf7b", colour = "black"
) + geom_point(data = DOWNblast_zygoteUHO0.05, shape = 21, size = 4, fill = "#af8dc3", colour = "black"
) + geom_label_repel(data = TOTblast_zygoteUHO0.05, aes(label = Symbol), force = 2,nudge_y = 1,
) + scale_fill_manual(values = cols) + scale_alpha_manual(values = alphas
) + theme_bw() +
  xlab("Expression change (log2FoldChange)")+
  ylab("Significance (-log10(padj))")+
  ggtitle(" Comparison of blastocyst stage and zygote stage (ultrahypoxia, 2nd library)")+ 
  xlim(-8, 8) +
  ylim(0, 50)

ggsave(ultrahypoxia_blas_vs_zygotevolano0.05, filename= "UHO_blastocyst_vs_zygot(padj<0.05).pdf", width = 10, height = 10)
write.table(DOWNblast_zygoteUHO0.05, file = "DOWNblast_zygoteUHO0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(UPbast_zygoteUHO0.05, file = "UPbast_zygoteUHO0.05.txt", sep = "\t", row.names = T, col.names = TRUE)

# UHO blastocyst vs 16c

ultrahypoxia_blas_vs_16cvol0.05 <- ultrahypoxia_blas_vs_16c %>% mutate(gene_type = case_when(log2FoldChange <= -1 & padj < 0.05 ~ "down", log2FoldChange >= 1 & padj < 0.05 ~ "up", TRUE ~ "ns"))
ultrahypoxia_blas_vs_16cvol0.05$Symbol<- rownames(ultrahypoxia_blas_vs_16cvol0.05) 

UPbast_16cUHO0.05 <- ultrahypoxia_blas_vs_16cvol0.05[ultrahypoxia_blas_vs_16cvol0.05$gene_type %in% "up",]
DOWNblast_16cUHO0.05 <- ultrahypoxia_blas_vs_16cvol0.05[ultrahypoxia_blas_vs_16cvol0.05$gene_type %in% "down",]
TOTblast_16cUHO0.05 <- rbind(UPbast_16cUHO0.05, DOWNblast_16cUHO0.05)
TOTblast_16cUHO0.05$Symbol<- rownames(TOTblast_16cUHO0.05)

ultrahypoxia_blas_vs_16cvolano0.05 <- ggplot(data = ultrahypoxia_blas_vs_16cvol0.05, aes(x=log2FoldChange, y=-log10(padj))
) + geom_point (aes(fill = gene_type), shape = 21, size = 2, color = "black"
) + geom_point(data = UPbast_16cUHO0.05 , shape = 21, size = 4, fill = "#7fbf7b", colour = "black"
) + geom_point(data = DOWNblast_16cUHO0.05, shape = 21, size = 4, fill = "#af8dc3", colour = "black"
) + geom_label_repel(data = TOTblast_16cUHO0.05, aes(label = Symbol), force = 2,nudge_y = 1,
) + scale_fill_manual(values = cols) + scale_alpha_manual(values = alphas
) + theme_bw() +
  xlab("Expression change (log2FoldChange)")+
  ylab("Significance (-log10(padj))")+
  ggtitle(" Comparison of blastocyst stage and 16c stage (ultrahypoxia, 2nd library)")+ 
  xlim(-8, 8) +
  ylim(0, 40)

ggsave(ultrahypoxia_blas_vs_16cvolano0.05, filename= "UHO_blastocyst_vs_16cUHO(padj<0.05)1.pdf", width = 10, height = 10)

library(gridExtra)
library(svglite)

fig5_blast_vs16C<- grid.arrange(hypoxia_blast_vs_16cvolano0.05, normoxia_blastocyst_vs_16cvolano0.05, ultrahypoxia_blas_vs_16cvolano0.05, ncol=3, nrow=1)
ggsave("fig5_blast_vs16C.pdf",fig5_blast_vs16C, width = 25, height = 10)
ggsave("fig5_blast_vs16C.svg", fig5_blast_vs16C, width = 20, height = 20)
```
#GO, KEGG, REACTOME 16c vs zygote

```{r}
library(clusterProfiler)
library(AnnotationDbi)
library(org.Bt.eg.db)
library(RColorBrewer)
library(ReactomePA)

#hypoxia
DOWN_16c_hyp0.05<- rownames(DOWN16c_zygotehyp0.05) 
GO_DOWN_16c_hyp0.05 <- enrichGO(gene = DOWN_16c_hyp0.05, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "BP")
GO_DOWN_16c_hyp0.05<-as.data.frame(GO_DOWN_16c_hyp0.05)

UP_16c_hyp0.05<- rownames(UP16c_zygotehyp0.05) 
GO_UP_16c_hyp0.05 <- enrichGO(gene = UP_16c_hyp0.05, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "BP")
GO_UP_16c_hyp0.05<-as.data.frame(GO_UP_16c_hyp0.05)

entrazDOWN_16c_hyp0.05<- mapIds(org.Bt.eg.db, keys = DOWN_16c_hyp0.05, column = "ENTREZID", keytype = "SYMBOL")
keggDOWN_16c_hyp0.05<- enrichKEGG(gene=entrazDOWN_16c_hyp0.05, organism = "bta")
keggDOWN_16c_hyp0.05 <- as.data.frame(keggDOWN_16c_hyp0.05)

entrazUP_16c_hyp0.05<- mapIds(org.Bt.eg.db, keys = UP_16c_hyp0.05, column = "ENTREZID", keytype = "SYMBOL")
keggUP_16c_hyp0.05<- enrichKEGG(gene=entrazUP_16c_hyp0.05, organism = "bta")
keggUP_16c_hyp0.05 <- as.data.frame(keggUP_16c_hyp0.05)

react_DOWN_16c_hyp0.05<- enrichPathway(gene=entrazDOWN_16c_hyp0.05, pvalueCutoff = 0.05, readable=TRUE, organism = "bovine" )
react_DOWN_16c_hyp0.05<- as.data.frame(react_DOWN_16c_hyp0.05)

react_UP_16c_hyp0.05<- enrichPathway(gene=entrazUP_16c_hyp0.05, pvalueCutoff = 0.05, readable=TRUE, organism = "bovine" )
react_UP_16c_hyp0.05<- as.data.frame(react_UP_16c_hyp0.05)

write.table(GO_DOWN_16c_hyp0.05, file = "GO_DOWN_16c_hyp0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(keggDOWN_16c_hyp0.05, file = "keggDOWN_16c_hyp0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(react_DOWN_16c_hyp0.05, file = "react_DOWN_16c_hyp0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(react_UP_16c_hyp0.05, file = "react_UP_16c_hyp0.05.txt", sep = "\t", row.names = T, col.names = TRUE)


#down normoxia
DOWN_16c_normn0.05<- rownames(DOWN16c_zygotenorm0.05) 
GO_DOWN_16c_normn0.05<- enrichGO(gene = DOWN_16c_normn0.05, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "BP")
GO_DOWN_16c_normn0.05<-as.data.frame(GO_DOWN_16c_normn0.05)

UP_16c_normn0.05<- rownames(UP16c_zygotenorm0.05) 
GO_UP_16c_normn0.05 <- enrichGO(gene = UP_16c_normn0.05, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "BP")
GO_UP_16c_normn0.05<-as.data.frame(GO_UP_16c_normn0.05)

entrazDOWN_16c_normn0.05<- mapIds(org.Bt.eg.db, keys = DOWN_16c_normn0.05, column = "ENTREZID", keytype = "SYMBOL")
keggDOWN_16c_normn0.05<- enrichKEGG(gene=entrazDOWN_16c_normn0.05, organism = "bta")
keggDOWN_16c_normn0.05 <- as.data.frame(keggDOWN_16c_normn0.05)

entrazUP_16c_normn0.05<- mapIds(org.Bt.eg.db, keys = UP_16c_normn0.05, column = "ENTREZID", keytype = "SYMBOL")
keggUP_16c_normn0.05<- enrichKEGG(gene=entrazUP_16c_normn0.05, organism = "bta")
keggUP_16c_normn0.05 <- as.data.frame(keggUP_16c_normn0.05)

react_DOWN_16c_normn0.05<- enrichPathway(gene=entrazDOWN_16c_normn0.05, pvalueCutoff = 0.05, readable=TRUE, organism = "bovine" )
react_DOWN_16c_normn0.05<- as.data.frame(react_DOWN_16c_normn0.05)

react_UP_16c_normn0.05<- enrichPathway(gene=entrazUP_16c_normn0.05, pvalueCutoff = 0.05, readable=TRUE, organism = "bovine" )
react_UP_16c_normn0.05<- as.data.frame(react_UP_16c_normn0.05)

write.table(GO_DOWN_16c_normn0.05, file = "GO_DOWN_16c_normn0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(GO_UP_16c_normn0.05, file = "GO_UP_16c_normn0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(keggDOWN_16c_normn0.05, file = "keggDOWN_16c_normn0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(keggUP_16c_normn0.05, file = "keggUP_16c_normn0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(react_DOWN_16c_normn0.05, file = "react_DOWN_16c_normn0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(react_UP_16c_normn0.05, file = "react_UP_16c_normn0.05.txt", sep = "\t", row.names = T, col.names = TRUE)


#ultrahypoxia

DOWN_16c_UHO0.05<- rownames(DOWN16c_zygoteUHO0.05) 
GO_DOWN_16c_UHO0.05<- enrichGO(gene = DOWN_16c_UHO0.05, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "BP")
GO_DOWN_16c_UHO0.05<-as.data.frame(GO_DOWN_16c_UHO0.05)

UP_16c_UHO0.05<- rownames(UP16c_zygoteUHO0.05) 
GO_UP_16c_UHO0.05 <- enrichGO(gene = UP_16c_UHO0.05, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "BP")
GO_UP_16c_UHO0.05<-as.data.frame(GO_UP_16c_UHO0.05)

entrazDOWN_16c_UHO0.05<- mapIds(org.Bt.eg.db, keys = DOWN_16c_UHO0.05, column = "ENTREZID", keytype = "SYMBOL")
keggDOWN_16c_UHO0.05<- enrichKEGG(gene=entrazDOWN_16c_UHO0.05, organism = "bta")
keggDOWN_16c_UHO0.05 <- as.data.frame(keggDOWN_16c_UHO0.05)

entrazUP_16c_UHO0.05<- mapIds(org.Bt.eg.db, keys = UP_16c_UHO0.05, column = "ENTREZID", keytype = "SYMBOL")
keggUP_16c_UHO0.05<- enrichKEGG(gene=entrazUP_16c_UHO0.05, organism = "bta")
keggUP_16c_UHO0.05 <- as.data.frame(keggUP_16c_UHO0.05)

react_DOWN_16c_UHO0.05<- enrichPathway(gene=entrazDOWN_16c_UHO0.05, pvalueCutoff = 0.05, readable=TRUE, organism = "bovine" )
react_DOWN_16c_UHO0.05<- as.data.frame(react_DOWN_16c_UHO0.05)

react_UP_16c_UHO0.05<- enrichPathway(gene=entrazUP_16c_UHO0.05, pvalueCutoff = 0.05, readable=TRUE, organism = "bovine" )
react_UP_16c_UHO0.05<- as.data.frame(react_UP_16c_UHO0.05)

write.table(GO_DOWN_16c_UHO0.05, file = "GO_DOWN_16c_UHO0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(GO_UP_16c_UHO0.05, file = "GO_UP_16c_UHO0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(keggDOWN_16c_UHO0.05, file = "keggDOWN_16c_UHO0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(keggUP_16c_UHO0.05, file = "keggUP_16c_UHO0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(react_DOWN_16c_UHO0.05, file = "react_DOWN_16c_UHO0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(react_UP_16c_UHO0.05, file = "react_UP_16c_UHO0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
```

#GO, KEGG, REACT blastocysts vs zygote

```{r}
#hypoxia 
DOWN_blast_vs_zygotehyp0.05<- rownames(DOWNblast_zygotehyp0.05) 
GO_DOWN_blast_vs_zygotehyp0.05 <- enrichGO(gene = DOWN_blast_vs_zygotehyp0.05, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "BP")
GO_DOWN_blast_vs_zygotehyp0.05<-as.data.frame(GO_DOWN_blast_vs_zygotehyp0.05)

UP_blast_vs_zygotehyp0.05<- rownames(UPbast_zygotehyp0.05) 
GO_UP_blast_vs_zygotehyp0.05 <- enrichGO(gene = UP_blast_vs_zygotehyp0.05, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "BP")
GO_UP_blast_vs_zygotehyp0.05<-as.data.frame(GO_UP_blast_vs_zygotehyp0.05)

entrazDOWN_blast_vs_zygotehyp0.05<- mapIds(org.Bt.eg.db, keys = DOWN_blast_vs_zygotehyp0.05 ,column = "ENTREZID", keytype = "SYMBOL")
keggDOWN_blast_vs_zygotehyp0.05<- enrichKEGG(gene=entrazDOWN_blast_vs_zygotehyp0.05, organism = "bta")
keggDOWN_blast_vs_zygotehyp0.05 <- as.data.frame(keggDOWN_blast_vs_zygotehyp0.05)

entrazUP_blast_vs_zygotehyp0.05<- mapIds(org.Bt.eg.db, keys = UP_blast_vs_zygotehyp0.05, column = "ENTREZID", keytype = "SYMBOL")
keggUP_blast_vs_zygotehyp0.05<- enrichKEGG(gene=entrazUP_blast_vs_zygotehyp0.05, organism = "bta")
keggUP_blast_vs_zygotehyp0.05 <- as.data.frame(keggUP_blast_vs_zygotehyp0.05)

react_DOWN_blast_vs_zygotehyp0.05<- enrichPathway(gene=entrazDOWN_blast_vs_zygotehyp0.05, pvalueCutoff = 0.05, readable=TRUE, organism = "bovine" )
react_DOWN_blast_vs_zygotehyp0.05<- as.data.frame(react_DOWN_blast_vs_zygotehyp0.05)

react_UP_blast_vs_zygotehyp0.05<- enrichPathway(gene=entrazUP_blast_vs_zygotehyp0.05, pvalueCutoff = 0.05, readable=TRUE, organism = "bovine" )
react_UP_blast_vs_zygotehyp0.05<- as.data.frame(react_UP_blast_vs_zygotehyp0.05)

#normoxia

DOWN_blast_vs_zygotenorm0.05<- rownames(DOWNblast_zygotenorm0.05) 
GO_DOWN_blast_vs_zygotenorm0.05 <- enrichGO(gene = DOWN_blast_vs_zygotenorm0.05, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "BP")
GO_DOWN_blast_vs_zygotenorm0.05<-as.data.frame(GO_DOWN_blast_vs_zygotenorm0.05)
#UPPPPPP
UP_blast_vs_zygotenorm0.05<- rownames(UPbast_zygotenorm0.05) 
GO_UP_blast_vs_zygotenorm0.05 <- enrichGO(gene = UP_blast_vs_zygotenorm0.05, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "BP")
GO_UP_blast_vs_zygotenorm0.05<-as.data.frame(GO_UP_blast_vs_zygotenorm0.05)

entrazDOWN_blast_vs_zygotenorm0.05<- mapIds(org.Bt.eg.db, keys = DOWN_blast_vs_zygotenorm0.05 ,column = "ENTREZID", keytype = "SYMBOL")
keggDOWN_blast_vs_zygotenorm0.05<- enrichKEGG(gene=entrazDOWN_blast_vs_zygotenorm0.05, organism = "bta")
keggDOWN_blast_vs_zygotenorm0.05 <- as.data.frame(keggDOWN_blast_vs_zygotenorm0.05)

entrazUP_blast_vs_zygotenorm0.05<- mapIds(org.Bt.eg.db, keys = UP_blast_vs_zygotenorm0.05, column = "ENTREZID", keytype = "SYMBOL")
keggUP_blast_vs_zygotenorm0.05<- enrichKEGG(gene=entrazUP_blast_vs_zygotenorm0.05, organism = "bta")
keggUP_blast_vs_zygotenorm0.05 <- as.data.frame(keggUP_blast_vs_zygotenorm0.05)

react_DOWN_blast_vs_zygotenorm0.05<- enrichPathway(gene=entrazDOWN_blast_vs_zygotenorm0.05, pvalueCutoff = 0.05, readable=TRUE, organism = "bovine" )
react_DOWN_blast_vs_zygotenorm0.05<- as.data.frame(react_DOWN_blast_vs_zygotenorm0.05)

react_UP_blast_vs_zygotenorm0.05<- enrichPathway(gene=entrazUP_blast_vs_zygotenorm0.05, pvalueCutoff = 0.05, readable=TRUE, organism = "bovine" )
react_UP_blast_vs_zygotenorm0.05<- as.data.frame(react_UP_blast_vs_zygotenorm0.05)

#d ultrahypoxia

DOWN_blast_vs_zygoteUHO0.05<- rownames(DOWNblast_zygoteUHO0.05) 
GO_DOWN_blast_vs_zygoteUHO0.05 <- enrichGO(gene = DOWN_blast_vs_zygoteUHO0.05, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "BP")
GO_DOWN_blast_vs_zygoteUHO0.05<-as.data.frame(GO_DOWN_blast_vs_zygoteUHO0.05)

UP_blast_vs_zygoteUHO0.05<- rownames(UPbast_zygoteUHO0.05) 
GO_UP_blast_vs_zygoteUHO0.05 <- enrichGO(gene = UP_blast_vs_zygoteUHO0.05, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "BP")
GO_UP_blast_vs_zygoteUHO0.05<-as.data.frame(GO_UP_blast_vs_zygoteUHO0.05)

entrazDOWN_blast_vs_zygoteUHO0.05<- mapIds(org.Bt.eg.db, keys = DOWN_blast_vs_zygoteUHO0.05 ,column = "ENTREZID", keytype = "SYMBOL")
keggDOWN_blast_vs_zygoteUHO0.05<- enrichKEGG(gene=entrazDOWN_blast_vs_zygoteUHO0.05, organism = "bta")
keggDOWN_blast_vs_zygoteUHO0.05 <- as.data.frame(keggDOWN_blast_vs_zygoteUHO0.05)

entrazUP_blast_vs_zygoteUHO0.05<- mapIds(org.Bt.eg.db, keys = UP_blast_vs_zygoteUHO0.05, column = "ENTREZID", keytype = "SYMBOL")
keggUP_blast_vs_zygoteUHO0.05<- enrichKEGG(gene=entrazUP_blast_vs_zygoteUHO0.05, organism = "bta")
keggUP_blast_vs_zygoteUHO0.05 <- as.data.frame(keggUP_blast_vs_zygoteUHO0.05)

react_DOWN_blast_vs_zygoteUHO0.05<- enrichPathway(gene=entrazDOWN_blast_vs_zygoteUHO0.05, pvalueCutoff = 0.05, readable=TRUE, organism = "bovine" )
react_DOWN_blast_vs_zygoteUHO0.05<- as.data.frame(react_DOWN_blast_vs_zygoteUHO0.05)

react_UP_blast_vs_zygoteUHO0.05<- enrichPathway(gene=entrazUP_blast_vs_zygoteUHO0.05, pvalueCutoff = 0.05, readable=TRUE, organism = "bovine" )
react_UP_blast_vs_zygoteUHO0.05<- as.data.frame(react_UP_blast_vs_zygoteUHO0.05)

```

#blastocyst of the HO vs zygote of UHO

```{r}

hypoxia_blas_vs_UHOzygote <- as.data.frame(results(dds1, contrast=c("Stage", "bHO", "zUHO")))
hypoxia_blas_vs_UHOzygote <- subset(hypoxia_blas_vs_UHOzygote, !is.na(padj) )

hypoxia_blas_vs_UHOzygotevol0.05 <- hypoxia_blas_vs_UHOzygote %>% mutate(gene_type = case_when(log2FoldChange <= -1 & padj < 0.05 ~ "down", log2FoldChange >= 1 & padj < 0.05 ~ "up", TRUE ~ "ns"))
hypoxia_blas_vs_UHOzygotevol0.05$Symbol<- rownames(hypoxia_blas_vs_UHOzygotevol0.05) 

UPHObast_zygoteUHO0.05 <- hypoxia_blas_vs_UHOzygotevol0.05[hypoxia_blas_vs_UHOzygotevol0.05$gene_type %in% "up",]
DOWNHOblast_zygoteUHO0.05 <- hypoxia_blas_vs_UHOzygotevol0.05[hypoxia_blas_vs_UHOzygotevol0.05$gene_type %in% "down",]
TOTHOblast_zygoteUHO0.05 <- rbind(UPHObast_zygoteUHO0.05, DOWNHOblast_zygoteUHO0.05)
TOTHOblast_zygoteUHO0.05$Symbol<- rownames(TOTHOblast_zygoteUHO0.05)

hypoxia_blas_vs_UHOzygotevolano0.05 <- ggplot(data = hypoxia_blas_vs_UHOzygotevol0.05, aes(x=log2FoldChange, y=-log10(padj))
) + geom_point (aes(fill = gene_type), shape = 21, size = 2, color = "black"
) + geom_point(data = UPHObast_zygoteUHO0.05 , shape = 21, size = 4, fill = "#7fbf7b", colour = "black"
) + geom_point(data = DOWNHOblast_zygoteUHO0.05, shape = 21, size = 4, fill = "#af8dc3", colour = "black"
) + geom_label_repel(data = TOTHOblast_zygoteUHO0.05, aes(label = Symbol), force = 2,nudge_y = 1,
) + scale_fill_manual(values = cols) + scale_alpha_manual(values = alphas
) + theme_bw() +
  xlab("Expression change (log2FoldChange)")+
  ylab("Significance (-log10(padj))")+
  ggtitle(" Comparison of blastocyst stage and zygote stage (ultrahypoxia, 2nd library)")+ 
  xlim(-8, 8) +
  ylim(0, 50)

```
#TRYING WITH COMBINING THE UHO and HO for the early stages 

```{r}
fluctuated_data<-read.delim("fluctuated_data.txt", header= TRUE, check.names = FALSE)
metadata<- read.table("metadataUHO.txt")
fluctuated_data <- fluctuated_data[, -c(13, 26, 38, 41)]
metadata<- metadata[-c(13,26, 38,41),]
```

```{r}
strt.seurat.obj <- CreateSeuratObject(counts = fluctuated_data, project = "STRT", min.cells = 10, min.features = 2000 )
strt.seurat.obj@meta.data <- metadata

```

```{r, message=FALSE}
strt.seurat.obj<- NormalizeData(strt.seurat.obj, normalization.method = "LogNormalize", scale.factor = 10000)
reads.p1<- fluctuated_data + 1 
reads.p1.spikes<- colSums(reads.p1[1:78, ])
strt.seurat.obj[["RNA"]]@data <- as(as.matrix(log(reads.p1/rep(reads.p1.spikes, each=nrow(reads.p1)))), "dgCMatrix")
all.genes <- row.names(strt.seurat.obj)
strt.seurat.obj <- ScaleData(strt.seurat.obj, features = all.genes)
```

```{r}
strt.seurat.obj <- RunPCA(strt.seurat.obj, features = all.genes, npcs = 33) 

pcaresults<- VizDimLoadings(strt.seurat.obj, dims = 1:2, reduction = "pca")

ggsave(pcaresults, filename= "pcaloadings, no16cHO and 4cUHO and NTC.pdf", height = 10, width = 10)


desired_order<- c("oocyte", "Zygote", "4cell", "8cell", "16cell", "blastocyst")
strt.seurat.obj$Developmental_stages<- factor(strt.seurat.obj$Developmental_stages, levels = desired_order)

pcaplot<-DimPlot(strt.seurat.obj, reduction = "pca", cols = c25, group.by = "Developmental_stages", shape.by = "Condition", label = T, label.size = 4, pt.size=3)+
  ggtitle("2nd library")

ggsave(pcaplot, filename= "pcaplot(no 16cHO(16)and4cUHO(38)and36.pdf", width = 10, height = 10)
ggsave(pcaplot, filename= "pcaplot(no 16cHO(16)and4cUHO(38).svg", width = 10, height = 10)

strt.seurat.obj <- RunUMAP(strt.seurat.obj, dims = 1:15, verbose = F)
umaptplot<- DimPlot(strt.seurat.obj,label.size = 4, cols = c25, group.by = "Developmental_stages", shape.by = "Condition", repel = T, label = T, pt.size = 4) +
  ggtitle("2nd library")
ggsave(umaptplot, filename= "UMAPplot(no 16cHO(16)and4cUHO(38), no26.pdf", width = 15, height = 10)
ggsave(umaptplot, filename= "UMAPplot(no 16cHO(16)and4cUHO(38), no26.svg", width = 10, height = 10)

strt.seurat.obj<- FindNeighbors(strt.seurat.obj, dims = 1:10)
strt.seurat.obj<-FindClusters(strt.seurat.obj, resolution = 1.2)
umapclusters <- DimPlot(strt.seurat.obj)

umapcluster0 <- FindMarkers(strt.seurat.obj, ident.1 = 0)
umapclust0markergenes<- rownames(umapcluster0)

umapcluster2 <- FindMarkers(strt.seurat.obj, ident.1 = 2)
umapclust2markergenes<-rownames(umapcluster2)
```

```{r}

dds <- DESeqDataSetFromMatrix(countData = fluctuated_data, 
                              colData = metadata, 
                              design = ~ Stage)
dds <- estimateSizeFactors(dds, controlGenes=1:77) #spike ins in the original dataset


keep <- rowSums(counts(dds)) >= 10
dds <- dds[keep,]
levels(dds$Stage)
dds1 <- DESeq(dds)
```


#hypoxia 
```{r}

hypoxiaUHO_8c_vs_zygote <- as.data.frame(results(dds1, contrast=c("Stage", "8cHO", "zHO")))
hypoxiaUHO_16c_vs_zygote <- as.data.frame(results(dds1, contrast=c("Stage", "16cHO", "zHO")))
hypoxiaUHO_blas_vs_zygote <- as.data.frame(results(dds1, contrast=c("Stage", "bHO", "zHO")))
hypoxiaUHO_blas_vs_16c <- as.data.frame(results(dds1, contrast=c("Stage", "bHO", "16cHO")))

hypoxiaUHO_8c_vs_zygote <- subset(hypoxiaUHO_8c_vs_zygote, !is.na(padj) )
hypoxiaUHO_16c_vs_zygote <- subset(hypoxiaUHO_16c_vs_zygote, !is.na(padj) )
hypoxiaUHO_blas_vs_zygote<- subset(hypoxiaUHO_blas_vs_zygote, !is.na(padj))
hypoxiaUHO_blas_vs_16c <- subset(hypoxiaUHO_blas_vs_16c, !is.na(padj))


hypoxiaUHO_8c_vs_zygotevol0.05 <- hypoxiaUHO_8c_vs_zygote%>% mutate(gene_type = case_when( log2FoldChange <= -1 & padj < 0.05 ~ "down", log2FoldChange >= 1 & padj < 0.05 ~ "up", TRUE ~ "ns"))
hypoxiaUHO_8c_vs_zygotevol0.05$Symbol<- rownames(hypoxiaUHO_8c_vs_zygotevol0.05) 

UP8c_zygotehypUHO0.05 <- hypoxiaUHO_8c_vs_zygotevol0.05[hypoxiaUHO_8c_vs_zygotevol0.05$gene_type %in% "up",]
DOWN8c_zygotehypUHO0.05 <- hypoxiaUHO_8c_vs_zygotevol0.05[hypoxiaUHO_8c_vs_zygotevol0.05$gene_type %in% "down",]
TOT8c_zygotehypUHO0.05 <- rbind(UP8c_zygotehypUHO0.05, DOWN8c_zygotehypUHO0.05)
TOT8c_zygotehypUHO0.05$Symbol<- rownames(TOT8c_zygotehypUHO0.05)


hypoxiaUHO_8c_vs_zygotevolano0.05 <- ggplot(data = hypoxiaUHO_8c_vs_zygotevol0.05, aes(x=log2FoldChange, y=-log10(padj))
) + geom_point (aes(fill = gene_type), shape = 21, size = 2, color = "black"
) + geom_point(data = UP8c_zygotehypUHO0.05 , shape = 21, size = 4, fill = "#7B9FA6", colour = "black"
) + geom_point(data = DOWN8c_zygotehypUHO0.05, shape = 21, size = 4, fill = "#A67F7B", colour = "black"
) + geom_label_repel(data = TOT8c_zygotehypUHO0.05, aes(label = Symbol), force = 2,nudge_y = 1,
) + scale_fill_manual(values = cols) + scale_alpha_manual(values = alphas
) + theme_bw() +
  xlab("Expression change (log2FoldChange)")+
  ylab("Significance (-log10(padj))")+
  ggtitle(" Comparison of 8cell stage and zygote stage (hypoxia, 2nd library) ")+ 
  xlim(-8, 8) +
  ylim(0, 50)



ggsave(hypoxiaUHO_8c_vs_zygotevolano0.05, filename= "hypoxiaUHO_8c_vs_zygot(padj<0.05)no26lat.pdf", width = 10, height = 10)
ggsave(hypoxiaUHO_8c_vs_zygotevolano0.05, filename= "hypoxiaUHO_8c_vs_zygot(padj<0.05)no26lat.svg", width = 10, height = 10)
write.table(DOWN8c_zygotehypUHO0.05, file = "DOWN8c_zygotehypUHO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)

#16c vs zygote hypoxia

hypoxiaUHO_16c_vs_zygotevol0.05 <- hypoxiaUHO_16c_vs_zygote %>% mutate(gene_type = case_when(log2FoldChange <= -1 & padj < 0.05 ~ "down", log2FoldChange >= 1 & padj < 0.05 ~ "up", TRUE ~ "ns"))
hypoxiaUHO_16c_vs_zygotevol0.05$Symbol<- rownames(hypoxiaUHO_16c_vs_zygotevol0.05) 


UP16c_zygotehypUHO0.05 <- hypoxiaUHO_16c_vs_zygotevol0.05[hypoxiaUHO_16c_vs_zygotevol0.05$gene_type %in% "up",]
DOWN16c_zygotehypUHO0.05 <- hypoxiaUHO_16c_vs_zygotevol0.05[hypoxiaUHO_16c_vs_zygotevol0.05$gene_type %in% "down",]
TOT16c_zygotehypUHO0.05 <- rbind(UP16c_zygotehypUHO0.05, DOWN16c_zygotehypUHO0.05)
TOT16c_zygotehypUHO0.05$Symbol<- rownames(TOT16c_zygotehypUHO0.05)


hypoxiaUHO_16c_vs_zygotevolano0.05 <- ggplot(data = hypoxiaUHO_16c_vs_zygotevol0.05, aes(x=log2FoldChange, y=-log10(padj))
) + geom_point (aes(fill = gene_type), shape = 21, size = 2, color = "black"
) + geom_point(data = UP16c_zygotehypUHO0.05 , shape = 21, size = 4, fill = "#7B9FA6", colour = "black"
) + geom_point(data = DOWN16c_zygotehypUHO0.05, shape = 21, size = 4, fill = "#A67F7B", colour = "black"
) + geom_label_repel(data = TOT16c_zygotehypUHO0.05, aes(label = Symbol), force = 2,nudge_y = 1,
) + scale_fill_manual(values = cols) + scale_alpha_manual(values = alphas
) + theme_bw() +
  xlab("Expression change (log2FoldChange)")+
  ylab("Significance (-log10(padj))")+
  ggtitle(" Comparison of 16cell stage and zygote stage (hypoxia, 2nd library)") + 
  xlim(-8, 8) +
  ylim(0, 50)

ggsave(hypoxiaUHO_16c_vs_zygotevolano0.05 , filename= "hypoxiaUHO_16c_vs_zygot(padj<0.05)no26lat.pdf", width = 10, height = 10)
ggsave(hypoxiaUHO_16c_vs_zygotevolano0.05 , filename= "hypoxiaUHO_16c_vs_zygot(padj<0.05)no26lat.svg", width = 10, height = 10)
write.table(DOWN16c_zygotehypUHO0.05, file = "DOWN16c_zygotehypUHO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(UP16c_zygotehypUHO0.05, file = "UP16c_zygotehypUHO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)

#volcano plot blastocyst vs zygote

hypoxiaUHO_blast_vs_zygotevol0.05 <- hypoxiaUHO_blas_vs_zygote%>% mutate(gene_type = case_when(log2FoldChange <= -1 & padj < 0.05 ~ "down", log2FoldChange >= 1 & padj < 0.05 ~ "up", TRUE ~ "ns"))
hypoxiaUHO_blast_vs_zygotevol0.05$Symbol<- rownames(hypoxiaUHO_blast_vs_zygotevol0.05) 

UPbast_zygotehypUHO0.05 <- hypoxiaUHO_blast_vs_zygotevol0.05[hypoxiaUHO_blast_vs_zygotevol0.05$gene_type %in% "up",]
DOWNblast_zygotehypUHO0.05 <- hypoxiaUHO_blast_vs_zygotevol0.05[hypoxiaUHO_blast_vs_zygotevol0.05$gene_type %in% "down",]
TOTblast_zygotehypUHO0.05 <- rbind(UPbast_zygotehypUHO0.05, DOWNblast_zygotehypUHO0.05)
TOTblast_zygotehypUHO0.05$Symbol<- rownames(TOTblast_zygotehypUHO0.05)

hypoxiaUHO_blast_vs_zygotevolano0.05 <- ggplot(data = hypoxiaUHO_blast_vs_zygotevol0.05, aes(x=log2FoldChange, y=-log10(padj))
) + geom_point (aes(fill = gene_type), shape = 21, size = 2, color = "black"
) + geom_point(data = UPbast_zygotehypUHO0.05 , shape = 21, size = 4, fill = "#7fbf7b", colour = "black"
) + geom_point(data = DOWNblast_zygotehypUHO0.05, shape = 21, size = 4, fill = "#af8dc3", colour = "black"
) + geom_label_repel(data = TOTblast_zygotehypUHO0.05, aes(label = Symbol), force = 2,nudge_y = 1,
) + scale_fill_manual(values = cols) + scale_alpha_manual(values = alphas
) + theme_bw() +
  xlab("Expression change (log2FoldChange)")+
  ylab("Significance (-log10(padj))")+
  ggtitle(" Comparison of blastocyst stage and zygote stage (hypoxia, 2nd library) ")+ 
  xlim(-8, 8) +
  ylim(0, 50)

ggsave(hypoxiaUHO_blast_vs_zygotevolano0.05, filename= "hypoxiaUHO_blastocyst_vs_zygot(padj<0.05).pdf", width = 10, height = 10)
write.table(DOWNblast_zygotehypUHO0.05, file = "DOWNblast_zygotehypUHO0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(UPbast_zygotehypUHO0.05, file = "UPbast_zygotehypUHO0.05.txt", sep = "\t", row.names = T, col.names = TRUE)

"#7B9FA6"
"#A67F7B"

#volcano plot blastocyst vs 16C ho

hypoxiaUHO_blast_vs_16cvol0.05 <- hypoxiaUHO_blas_vs_16c%>% mutate(gene_type = case_when(log2FoldChange <= -1 & padj < 0.05 ~ "down", log2FoldChange >= 1 & padj < 0.05 ~ "up", TRUE ~ "ns"))
hypoxiaUHO_blast_vs_16cvol0.05$Symbol<- rownames(hypoxiaUHO_blast_vs_16cvol0.05) 

UPbast_16chypUHO0.05 <- hypoxiaUHO_blast_vs_16cvol0.05[hypoxiaUHO_blast_vs_16cvol0.05$gene_type %in% "up",]
DOWNblast_16chypUHO0.05 <- hypoxiaUHO_blast_vs_16cvol0.05[hypoxiaUHO_blast_vs_16cvol0.05$gene_type %in% "down",]
TOTblast_16chypUHO0.05 <- rbind(UPbast_16chypUHO0.05, DOWNblast_16chypUHO0.05)
TOTblast_16chypUHO0.05$Symbol<- rownames(TOTblast_16chypUHO0.05)

hypoxiaUHO_blast_vs_16cvolano0.05 <- ggplot(data = hypoxiaUHO_blast_vs_16cvol0.05, aes(x=log2FoldChange, y=-log10(padj))
) + geom_point (aes(fill = gene_type), shape = 21, size = 2, color = "black"
) + geom_point(data = UPbast_16chypUHO0.05 , shape = 21, size = 4, fill = "#7B9FA6", colour = "black"
) + geom_point(data = DOWNblast_16chypUHO0.05, shape = 21, size = 4, fill = "#A67F7B", colour = "black"
) + geom_label_repel(data = TOTblast_16chypUHO0.05, aes(label = Symbol), force = 2,nudge_y = 1,
) + scale_fill_manual(values = cols) + scale_alpha_manual(values = alphas
) + theme_bw() +
  xlab("Expression change (log2FoldChange)")+
  ylab("Significance (-log10(padj))")+
  theme(legend.position = "none")+
  xlim(-8, 8) +
  ylim(0, 40)

ggsave(hypoxiaUHO_blast_vs_16cvolano0.05, filename= "hypoxiaUHO_blastocyst_vs_16c(padj<0.05)no26lat.pdf", width = 10, height = 10)
ggsave(hypoxiaUHO_blast_vs_16cvolano0.05, filename= "hypoxiaUHO_blastocyst_vs_16c(padj<0.05)no26lat.svg", width = 10, height = 10)
write.table(DOWNblast_16chypUHO0.05, file = "DOWNblast_16chypUHO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(UPbast_16chypUHO0.05, file = "UPbast_16chypUHO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)
```

#ULTRAHYPOXIA
```{r}
ultrahypoxia_blas_vs_HOzygote <- as.data.frame(results(dds1, contrast=c("Stage", "bUHO", "zHO")))
ultrahypoxia_blas_vs_HO16c <- as.data.frame(results(dds1, contrast=c("Stage", "bUHO", "16cHO")))

ultrahypoxia_blas_vs_HOzygote<- subset(ultrahypoxia_blas_vs_HOzygote, !is.na(padj) )
ultrahypoxia_blas_vs_HO16c <- subset(ultrahypoxia_blas_vs_HO16c, !is.na(padj) )
# UHO blastocyst vs zygote

ultrahypoxia_blas_vs_HOzygotevol0.05 <- ultrahypoxia_blas_vs_HOzygote %>% mutate(gene_type = case_when(log2FoldChange <= -1 & padj < 0.05 ~ "down", log2FoldChange >= 1 & padj < 0.05 ~ "up", TRUE ~ "ns"))
ultrahypoxia_blas_vs_HOzygotevol0.05$Symbol<- rownames(ultrahypoxia_blas_vs_HOzygotevol0.05) 

UPbast_zygoteUHO_HO_0.05 <- ultrahypoxia_blas_vs_HOzygotevol0.05[ultrahypoxia_blas_vs_HOzygotevol0.05$gene_type %in% "up",]
DOWNblast_zygoteUHO_HO_0.05 <- ultrahypoxia_blas_vs_HOzygotevol0.05[ultrahypoxia_blas_vs_HOzygotevol0.05$gene_type %in% "down",]
TOTblast_zygoteUHO_HO_0.05 <- rbind(UPbast_zygoteUHO_HO_0.05, DOWNblast_zygoteUHO_HO_0.05)
TOTblast_zygoteUHO_HO_0.05$Symbol<- rownames(TOTblast_zygoteUHO_HO_0.05)

ultrahypoxia_blas_vs_HOzygotevolano0.05 <- ggplot(data = ultrahypoxia_blas_vs_HOzygotevol0.05, aes(x=log2FoldChange, y=-log10(padj))
) + geom_point (aes(fill = gene_type), shape = 21, size = 2, color = "black"
) + geom_point(data = UPbast_zygoteUHO_HO_0.05 , shape = 21, size = 4, fill = "#7fbf7b", colour = "black"
) + geom_point(data = DOWNblast_zygoteUHO_HO_0.05, shape = 21, size = 4, fill = "#af8dc3", colour = "black"
) + geom_label_repel(data = TOTblast_zygoteUHO_HO_0.05, aes(label = Symbol), force = 2,nudge_y = 1,
) + scale_fill_manual(values = cols) + scale_alpha_manual(values = alphas
) + theme_bw() +
  xlab("Expression change (log2FoldChange)")+
  ylab("Significance (-log10(padj))")+
  ggtitle(" Comparison of blastocyst stage and zygote stage (ultrahypoxia, 2nd library)")+ 
  xlim(-8, 8) +
  ylim(0, 50)

ggsave(ultrahypoxia_blas_vs_HOzygotevolano0.05, filename= "UHO_blastocyst_vs_HOzygot(padj<0.05)no26.pdf", width = 10, height = 10)
write.table(DOWNblast_zygoteUHO_HO_0.05, file = "DOWNblast_zygoteUHO_HO_0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(UPbast_zygoteUHO_HO_0.05, file = "UPbast_zygoteUHO_HO_0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)

"#7B9FA6"
"#A67F7B"

# UHO blastocyst vs 16c

ultrahypoxia_blas_vs_HO16cvol0.05 <- ultrahypoxia_blas_vs_HO16c %>% mutate(gene_type = case_when(log2FoldChange <= -1 & padj < 0.05 ~ "down", log2FoldChange >= 1 & padj < 0.05 ~ "up", TRUE ~ "ns"))
ultrahypoxia_blas_vs_HO16cvol0.05$Symbol<- rownames(ultrahypoxia_blas_vs_HO16cvol0.05) 

UPbast_16cUHO_HO_0.05 <- ultrahypoxia_blas_vs_HO16cvol0.05[ultrahypoxia_blas_vs_HO16cvol0.05$gene_type %in% "up",]
DOWNblast_16cUHO_HO_0.05 <- ultrahypoxia_blas_vs_HO16cvol0.05[ultrahypoxia_blas_vs_HO16cvol0.05$gene_type %in% "down",]
TOTblast_16cUHO_HO_0.05 <- rbind(UPbast_16cUHO_HO_0.05, DOWNblast_16cUHO_HO_0.05)
TOTblast_16cUHO_HO_0.05$Symbol<- rownames(TOTblast_16cUHO_HO_0.05)

ultrahypoxia_blas_vs_HO16cvolano0.05 <- ggplot(data = ultrahypoxia_blas_vs_HO16cvol0.05, aes(x=log2FoldChange, y=-log10(padj))
) + geom_point (aes(fill = gene_type), shape = 21, size = 2, color = "black"
) + geom_point(data = UPbast_16cUHO_HO_0.05 , shape = 21, size = 4, fill = "#7B9FA6", colour = "black"
) + geom_point(data = DOWNblast_16cUHO_HO_0.05, shape = 21, size = 4, fill = "#A67F7B", colour = "black"
) + geom_label_repel(data = TOTblast_16cUHO_HO_0.05, aes(label = Symbol), force = 2,nudge_y = 1,
) + scale_fill_manual(values = cols) + scale_alpha_manual(values = alphas
) + theme_bw() +
  xlab("Expression change (log2FoldChange)")+
  ylab("Significance (-log10(padj))")+
  theme(legend.position = "none")+
  xlim(-8, 8) +
  ylim(0, 40)

ggsave(ultrahypoxia_blas_vs_HO16cvolano0.05, filename= "UHO_blastocyst_vs_HO16c(padj<0.05)no26lat.pdf", width = 10, height = 10)
ggsave(ultrahypoxia_blas_vs_HO16cvolano0.05, filename= "UHO_blastocyst_vs_HO16c(padj<0.05)no26lat.svg", width = 10, height = 10)
write.table(UPbast_16cUHO_HO_0.05, file = "UPbast_16cUHO_HO_0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(DOWNblast_16cUHO_HO_0.05, file = "DOWNblast_16cUHO_HO_0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)
```

#NORMOXIA; UHO_HO
```{r}

normoxia_8c_vs_zygoteUHO_HO <- as.data.frame(results(dds1, contrast=c("Stage", "8cNO", "zNO")))
normoxia_16c_vs_zygoteUHO_HO <- as.data.frame(results(dds1, contrast=c("Stage", "16cNO", "zNO")))
normoxia_blas_vs_zygoteUHO_HO <- as.data.frame(results(dds1, contrast=c("Stage", "bNO", "zNO")))
normoxia_blas_vs_16cUHO_HO <- as.data.frame(results(dds1, contrast=c("Stage", "bNO", "16cNO")))

#cleaning up the tables by removing samples that have padj NA and spikeins

normoxia_8c_vs_zygoteUHO_HO <- subset(normoxia_8c_vs_zygoteUHO_HO, !is.na(padj) )
normoxia_16c_vs_zygoteUHO_HO <- subset(normoxia_16c_vs_zygoteUHO_HO, !is.na(padj) )
normoxia_blas_vs_zygoteUHO_HO<- subset(normoxia_blas_vs_zygoteUHO_HO, !is.na(padj) )
normoxia_blas_vs_16cUHO_HO <- subset(normoxia_blas_vs_16cUHO_HO, !is.na(padj) )

# volcano plots for normoxia
#8c vs zygote

normoxia_8c_vs_zygoteUHO_HOvol0.05 <- normoxia_8c_vs_zygoteUHO_HO %>% mutate(gene_type = case_when(log2FoldChange <= -1 & padj < 0.05 ~ "down", log2FoldChange >= 1 & padj < 0.05 ~ "up", TRUE ~ "ns"))
normoxia_8c_vs_zygoteUHO_HOvol0.05$Symbol<- rownames(normoxia_8c_vs_zygoteUHO_HOvol0.05) 

UP8c_zygotenormUHO_HO0.05 <- normoxia_8c_vs_zygoteUHO_HOvol0.05[normoxia_8c_vs_zygoteUHO_HOvol0.05$gene_type %in% "up",]
DOWN8c_zygotenormUHO_HO0.05 <- normoxia_8c_vs_zygoteUHO_HOvol0.05[normoxia_8c_vs_zygoteUHO_HOvol0.05$gene_type %in% "down",]
TOT8c_zygotenormUHO_HO0.05<- rbind(UP8c_zygotenormUHO_HO0.05, DOWN8c_zygotenormUHO_HO0.05)
TOT8c_zygotenormUHO_HO0.05$Symbol<- rownames(TOT8c_zygotenormUHO_HO0.05)


normoxia_8c_vs_zygoteUHO_HOvolano0.05 <- ggplot(data = normoxia_8c_vs_zygoteUHO_HOvol0.05, aes(x=log2FoldChange, y=-log10(padj))
) + geom_point (aes(fill = gene_type), shape = 21, size = 2, color = "black"
) + geom_point(data = UP8c_zygotenormUHO_HO0.05 , shape = 21, size = 4, fill = "#7B9FA6", colour = "black"
) + geom_point(data = DOWN8c_zygotenormUHO_HO0.05, shape = 21, size = 4, fill = "#A67F7B", colour = "black"
) + geom_label_repel(data = TOT8c_zygotenormUHO_HO0.05, aes(label = Symbol), force = 2,nudge_y = 1,
) + scale_fill_manual(values = cols) + scale_alpha_manual(values = alphas
) + theme_bw() +
  xlab("Expression change (log2FoldChange)")+
  ylab("Significance (-log10(padj))")+
  ggtitle(" Comparison of 8cell stage and zygote stage (normoxia, 2nd library) ")+ 
  xlim(-8, 8) +
  ylim(0, 50)

ggsave(normoxia_8c_vs_zygoteUHO_HOvolano0.05, filename= "normoxia_8c_vs_zygotUHO_HO(padj<0.05)no26lat.pdf", width = 10, height = 10)
ggsave(normoxia_8c_vs_zygoteUHO_HOvolano0.05, filename= "normoxia_8c_vs_zygotUHO_HO(padj<0.05)no26lat.svg", width = 10, height = 10)
write.table(DOWN8c_zygotenormUHO_HO0.05, file = "DOWN8c_zygotenormUHO_HO0.05.txt", sep = "\t", row.names = T, col.names = TRUE)

#16c vs zygote

normoxia_16c_vs_zygoteUHO_HOvol0.05 <- normoxia_16c_vs_zygoteUHO_HO %>% mutate(gene_type = case_when(log2FoldChange <= -1 & padj < 0.05 ~ "down", log2FoldChange >= 1 & padj < 0.05 ~ "up", TRUE ~ "ns"))
normoxia_16c_vs_zygoteUHO_HOvol0.05$Symbol<- rownames(normoxia_16c_vs_zygoteUHO_HOvol0.05) 


UP16c_zygotenormUHO_HO0.05 <- normoxia_16c_vs_zygoteUHO_HOvol0.05[normoxia_16c_vs_zygoteUHO_HOvol0.05$gene_type %in% "up",]
DOWN16c_zygotenormUHO_HO0.05 <- normoxia_16c_vs_zygoteUHO_HOvol0.05[normoxia_16c_vs_zygoteUHO_HOvol0.05$gene_type %in% "down",]
TOT16c_zygotenormUHO_HO0.05 <- rbind(UP16c_zygotenormUHO_HO0.05, DOWN16c_zygotenormUHO_HO0.05)
TOT16c_zygotenormUHO_HO0.05$Symbol<- rownames(TOT16c_zygotenormUHO_HO0.05)


normoxia_16c_vs_zygoteUHO_HOvolano0.05 <- ggplot(data = normoxia_16c_vs_zygoteUHO_HOvol0.05, aes(x=log2FoldChange, y=-log10(padj))
) + geom_point (aes(fill = gene_type), shape = 21, size = 2, color = "black"
) + geom_point(data = UP16c_zygotenormUHO_HO0.05, shape = 21, size = 4, fill = "#7B9FA6", colour = "black"
) + geom_point(data = DOWN16c_zygotenormUHO_HO0.05, shape = 21, size = 4, fill = "#A67F7B", colour = "black"
) + geom_label_repel(data = TOT16c_zygotenormUHO_HO0.05, aes(label = Symbol), force = 2,nudge_y = 1,
) + scale_fill_manual(values = cols) + scale_alpha_manual(values = alphas
) + theme_bw() +
  xlab("Expression change (log2FoldChange)")+
  ylab("Significance (-log10(padj))")+
  ggtitle(" Comparison of 16cell stage and zygote stage(normoxia, 2nd library)")+ 
  xlim(-8, 8) +
  ylim(0, 50)

ggsave(normoxia_16c_vs_zygoteUHO_HOvolano0.05 , filename= "normoxia_16c_vs_zygoteUHO_HOvolano(padj<0.05)no26lat.pdf", width = 10, height = 10)
ggsave(normoxia_16c_vs_zygoteUHO_HOvolano0.05 , filename= "normoxia_16c_vs_zygoteUHO_HOvolano(padj<0.05)no26lat.svg", width = 10, height = 10)
write.table(DOWN16c_zygotenormUHO_HO0.05, file = "DOWN16c_zygotenormUHO_HO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(UP16c_zygotenormUHO_HO0.05, file = "UP16c_zygotenormUHO_HO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)

# blastocyst vs zygote

normoxia_blas_vs_zygoteUHO_HOvol0.05 <- normoxia_blas_vs_zygoteUHO_HO%>% mutate(gene_type = case_when(log2FoldChange <= -1 & padj < 0.05 ~ "down", log2FoldChange >= 1 & padj < 0.05 ~ "up", TRUE ~ "ns"))
normoxia_blas_vs_zygoteUHO_HOvol0.05$Symbol<- rownames(normoxia_blas_vs_zygoteUHO_HOvol0.05) 

UPbast_zygotenormUHO_HO0.05 <- normoxia_blas_vs_zygoteUHO_HOvol0.05[normoxia_blas_vs_zygoteUHO_HOvol0.05$gene_type %in% "up",]
DOWNblast_zygotenormUHO_HO0.05 <- normoxia_blas_vs_zygoteUHO_HOvol0.05[normoxia_blas_vs_zygoteUHO_HOvol0.05$gene_type %in% "down",]
TOTblast_zygotenormUHO_HO0.05 <- rbind(UPbast_zygotenormUHO_HO0.05, DOWNblast_zygotenormUHO_HO0.05)
TOTblast_zygotenormUHO_HO0.05$Symbol<- rownames(TOTblast_zygotenormUHO_HO0.05)

normoxia_blast_vs_zygoteUHO_HOvolano0.05 <- ggplot(data = normoxia_blas_vs_zygoteUHO_HOvol0.05, aes(x=log2FoldChange, y=-log10(padj))
) + geom_point (aes(fill = gene_type), shape = 21, size = 2, color = "black"
) + geom_point(data = UPbast_zygotenormUHO_HO0.05 , shape = 21, size = 4, fill = "#7fbf7b", colour = "black"
) + geom_point(data = DOWNblast_zygotenormUHO_HO0.05, shape = 21, size = 4, fill = "#af8dc3", colour = "black"
) + geom_label_repel(data = TOTblast_zygotenormUHO_HO0.05, aes(label = Symbol), force = 2,nudge_y = 1,
) + scale_fill_manual(values = cols) + scale_alpha_manual(values = alphas
) + theme_bw() +
  xlab("Expression change (log2FoldChange)")+
  ylab("Significance (-log10(padj))")+
  ggtitle(" Comparison of blastocyst stage and zygote stage (normoxia, 2ns library) ")+ 
  xlim(-8, 8) +
  ylim(0, 50)

ggsave(normoxia_blast_vs_zygoteUHO_HOvolano0.05, filename= "normoxia_blastocyst_vs_zygotUHO_HO(padj<0.05).pdf", width = 10, height = 10)
write.table(DOWNblast_zygotenormUHO_HO0.05, file = "DOWNblast_zygotenormUHO_HO0.05.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(UPbast_zygotenormUHO_HO0.05, file = "UPbast_zygotenormUHO_HO0.05.txt", sep = "\t", row.names = T, col.names = TRUE)

#volcano plot blastocyst vs 16c
"#7B9FA6"
"#A67F7B"
normoxia_blas_vs_16cUHO_HOvol0.05 <- normoxia_blas_vs_16cUHO_HO %>% mutate(gene_type = case_when(log2FoldChange <= -1 & padj < 0.05 ~ "down", log2FoldChange >= 1 & padj < 0.05 ~ "up", TRUE ~ "ns"))
normoxia_blas_vs_16cUHO_HOvol0.05$Symbol<- rownames(normoxia_blas_vs_16cUHO_HOvol0.05) 

UPbast_16cnormUHO_HO0.05 <- normoxia_blas_vs_16cUHO_HOvol0.05[normoxia_blas_vs_16cUHO_HOvol0.05$gene_type %in% "up",]
DOWNblast_16cnormUHO_HO0.05 <- normoxia_blas_vs_16cUHO_HOvol0.05[normoxia_blas_vs_16cUHO_HOvol0.05$gene_type %in% "down",]
TOTblast_16cnormUHO_HO0.05 <- rbind(UPbast_16cnormUHO_HO0.05, DOWNblast_16cnormUHO_HO0.05)
TOTblast_16cnormUHO_HO0.05$Symbol<- rownames(TOTblast_16cnormUHO_HO0.05)

normoxia_blastocyst_vs_16cUHO_HOvolano0.05 <- ggplot(data = normoxia_blas_vs_16cUHO_HOvol0.05, aes(x=log2FoldChange, y=-log10(padj))
) + geom_point (aes(fill = gene_type), shape = 21, size = 2, color = "black"
) + geom_point(data = UPbast_16cnormUHO_HO0.05 , shape = 21, size = 4, fill = "#7B9FA6", colour = "black"
) + geom_point(data = DOWNblast_16cnormUHO_HO0.05, shape = 21, size = 4, fill = "#A67F7B", colour = "black"
) + geom_label_repel(data = TOTblast_16cnormUHO_HO0.05, aes(label = Symbol), force = 2,nudge_y = 1,
) + scale_fill_manual(values = cols) + scale_alpha_manual(values = alphas
) + theme_bw()+
  xlab("Expression change (log2FoldChange)")+
  ylab("Significance (-log10(padj))")+
  theme(legend.position = "none")+
  xlim(-8, 8) +
  ylim(0, 40)


ggsave(normoxia_blastocyst_vs_16cUHO_HOvolano0.05 , filename= "normoxia_blastocyst_vs_16cUHO_HOvolano(padj<0.05)no26lat.pdf", width = 10, height = 10)
ggsave(normoxia_blastocyst_vs_16cUHO_HOvolano0.05 , filename= "normoxia_blastocyst_vs_16cUHO_HOvolano(padj<0.05)no26lat.svg", width = 10, height = 10)
write.table(DOWNblast_16cnormUHO_HO0.05, file = "DOWNblast_16cnormUHO_HO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(UPbast_16cnormUHO_HO0.05, file = "UPbast_16cnormUHO_HO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)

figure5<- grid.arrange(hypoxiaUHO_blast_vs_16cvolano0.05, normoxia_blastocyst_vs_16cUHO_HOvolano0.05, ultrahypoxia_blas_vs_HO16cvolano0.05, ncol=3, nrow=1)
ggsave("fig5.pdf",figure5, width = 25, height = 10)
ggsave("fig5.svg",figure5 , width = 10, height = 8)
```

#GO,KEGG,REACT- 16C VS ZYGOTE
```{r}

#hypoxia
DOWN16c_hypUHO0.05<- rownames(DOWN16c_zygotehypUHO0.05) 
GO_DOWN16c_hypUHO0.05 <- enrichGO(gene = DOWN16c_hypUHO0.05, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "BP")
GO_DOWN16c_hypUHO0.05<-as.data.frame(GO_DOWN16c_hypUHO0.05)

UP16c_hypUHO0.05<- rownames(UP16c_zygotehypUHO0.05) 
GO_UP16c_hypUHO0.05 <- enrichGO(gene = UP16c_hypUHO0.05, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "BP")
GO_UP16c_hypUHO0.05<-as.data.frame(GO_UP16c_hypUHO0.05)

GO_UP16c_hypUHO0.05MF <- enrichGO(gene = UP16c_hypUHO0.05, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "MF")
GO_UP16c_hypUHO0.05MF<-as.data.frame(GO_UP16c_hypUHO0.05MF)

GO_UP16c_hypUHO0.05ALL <- enrichGO(gene = UP16c_hypUHO0.05, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "ALL")
GO_UP16c_hypUHO0.05ALL<-as.data.frame(GO_UP16c_hypUHO0.05MF)

entrazDOWN16c_hypUHO0.05<- mapIds(org.Bt.eg.db, keys = DOWN16c_hypUHO0.05, column = "ENTREZID", keytype = "SYMBOL")
keggDOWN16c_hypUHO0.05<- enrichKEGG(gene=entrazDOWN16c_hypUHO0.05, organism = "bta")
keggDOWN16c_hypUHO0.05 <- as.data.frame(keggDOWN16c_hypUHO0.05)

entrazUP16c_hypUHO0.05<- mapIds(org.Bt.eg.db, keys = UP16c_hypUHO0.05, column = "ENTREZID", keytype = "SYMBOL")
keggUP16c_hypUHO0.05<- enrichKEGG(gene=entrazUP16c_hypUHO0.05, organism = "bta")
keggUP16c_hypUHO0.05 <- as.data.frame(keggUP16c_hypUHO0.05)

react_DOWN16c_hypUHO0.05<- enrichPathway(gene=entrazDOWN16c_hypUHO0.05, pvalueCutoff = 0.05, readable=TRUE, organism = "bovine" )
react_DOWN16c_hypUHO0.05<- as.data.frame(react_DOWN16c_hypUHO0.05)


react_UP16c_hypUHO0.05<- enrichPathway(gene=entrazUP16c_hypUHO0.05, pvalueCutoff = 0.05, readable=TRUE, organism = "bovine" )
react_UP16c_hypUHO0.05<- as.data.frame(react_UP16c_hypUHO0.05)

write.table(GO_DOWN16c_hypUHO0.05, file = "GO_DOWN16c_hypUHO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(keggDOWN16c_hypUHO0.05, file = "keggDOWN16c_hypUHO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(react_DOWN16c_hypUHO0.05, file = "react_DOWN16c_hypUHO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(react_UP16c_hypUHO0.05, file = "react_UP16c_hypUHO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)


#down normoxia
UP16c_zygotenormUHO_HO0.05 
DOWN16c_zygotenormUHO_HO0.05

DOWN16c_normUHO_HO0.05<- rownames(DOWN16c_zygotenormUHO_HO0.05) 
GO_DOWN16c_normUHO_HO0.05<- enrichGO(gene = DOWN16c_normUHO_HO0.05, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "BP")
GO_DOWN16c_normUHO_HO0.05<-as.data.frame(GO_DOWN16c_normUHO_HO0.05)

UP16c_normUHO_HO0.05<- rownames(UP16c_zygotenormUHO_HO0.05) 
GO_UP16c_normUHO_HO0.05 <- enrichGO(gene = UP16c_normUHO_HO0.05, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "BP")
GO_UP16c_normUHO_HO0.05<-as.data.frame(GO_UP16c_normUHO_HO0.05)

GO_UP16c_normUHO_HO0.05MF <- enrichGO(gene = UP16c_normUHO_HO0.05, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "MF")
GO_UP16c_normUHO_HO0.05MF<-as.data.frame(GO_UP16c_normUHO_HO0.05MF)

entrazDOWN16c_normUHO_HO0.05<- mapIds(org.Bt.eg.db, keys = DOWN16c_normUHO_HO0.05, column = "ENTREZID", keytype = "SYMBOL")
keggDOWN16c_normUHO_HO0.05<- enrichKEGG(gene=entrazDOWN16c_normUHO_HO0.05, organism = "bta")
keggDOWN16c_normUHO_HO0.05 <- as.data.frame(keggDOWN16c_normUHO_HO0.05)

entrazUP16c_normUHO_HO0.05<- mapIds(org.Bt.eg.db, keys = UP16c_normUHO_HO0.05, column = "ENTREZID", keytype = "SYMBOL")
keggUP16c_normUHO_HO0.05<- enrichKEGG(gene=entrazUP16c_normUHO_HO0.05, organism = "bta")
keggUP16c_normUHO_HO0.05 <- as.data.frame(keggUP16c_normUHO_HO0.05)

react_DOWN16c_normUHO_HO0.05<- enrichPathway(gene=entrazDOWN16c_normUHO_HO0.05, pvalueCutoff = 0.05, readable=TRUE, organism = "bovine" )
react_DOWN16c_normUHO_HO0.05<- as.data.frame(react_DOWN16c_normUHO_HO0.05)

react_UP16c_normUHO_HO0.05<- enrichPathway(gene=entrazUP16c_normUHO_HO0.05, pvalueCutoff = 0.05, readable=TRUE, organism = "bovine" )
react_UP16c_normUHO_HO0.05<- as.data.frame(react_UP16c_normUHO_HO0.05)

write.table(GO_DOWN16c_normUHO_HO0.05, file = "GO_DOWN16c_normUHO_HO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(GO_UP16c_normUHO_HO0.05, file = "GO_UP16c_normUHO_HO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(keggDOWN16c_normUHO_HO0.05, file = "keggDOWN16c_normUHO_HO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(keggUP16c_normUHO_HO0.05, file = "keggUP16c_normUHO_HO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(react_DOWN16c_normUHO_HO0.05, file = "react_DOWN16c_normUHO_HO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(react_UP16c_normUHO_HO0.05, file = "react_UP16c_normUHO_HO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)
```

#BLASTOCYST VS 16C

```{r}
#NORMOXIA

DOWNblast_16cNO_UHO_HO0.05<- rownames(DOWNblast_16cnormUHO_HO0.05) 
GO_DOWNblast_16cNO_UHO_HO0.05<- enrichGO(gene = DOWNblast_16cNO_UHO_HO0.05, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "BP")
GO_DOWNblast_16cNO_UHO_HO0.05<-as.data.frame(GO_DOWNblast_16cNO_UHO_HO0.05)

UPbast_16cNO_UHO_HO0.05 <- rownames(UPbast_16cnormUHO_HO0.05) 
GO_UPbast_16cNO_UHO_HO0.05 <- enrichGO(gene = UPbast_16cNO_UHO_HO0.05, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "BP")
GO_UPbast_16cNO_UHO_HO0.05<-as.data.frame(GO_UPbast_16cNO_UHO_HO0.05)

entrazDOWNblast_16cNO_UHO_HO0.05<- mapIds(org.Bt.eg.db, keys = DOWNblast_16cNO_UHO_HO0.05, column = "ENTREZID", keytype = "SYMBOL")
keggDOWNblast_16cNO_UHO_HO0.05<- enrichKEGG(gene=entrazDOWNblast_16cNO_UHO_HO0.05, organism = "bta")
keggDOWNblast_16cNO_UHO_HO0.05 <- as.data.frame(keggDOWNblast_16cNO_UHO_HO0.05)

entrazUPbast_16cNO_UHO_HO0.05<- mapIds(org.Bt.eg.db, keys = UPbast_16cNO_UHO_HO0.05, column = "ENTREZID", keytype = "SYMBOL")
keggUPbast_16cNO_UHO_HO0.05<- enrichKEGG(gene=entrazUPbast_16cNO_UHO_HO0.05, organism = "bta")
keggUPbast_16cNO_UHO_HO0.05 <- as.data.frame(keggUPbast_16cNO_UHO_HO0.05)

react_DOWNblast_16cNO_UHO_HO0.05<- enrichPathway(gene=entrazDOWNblast_16cNO_UHO_HO0.05, pvalueCutoff = 0.05, readable=TRUE, organism = "bovine" )
react_DOWNblast_16cNO_UHO_HO0.05<- as.data.frame(react_DOWNblast_16cNO_UHO_HO0.05)

react_UPbast_16cNO_UHO_HO0.05<- enrichPathway(gene=entrazUPbast_16cNO_UHO_HO0.05, pvalueCutoff = 0.05, readable=TRUE, organism = "bovine" )
react_UPbast_16cNO_UHO_HO0.05<- as.data.frame(react_UPbast_16cNO_UHO_HO0.05)

write.table(GO_DOWNblast_16cNO_UHO_HO0.05, file = "GO_DOWNblast_16cNO_UHO_HO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(GO_UPbast_16cNO_UHO_HO0.05, file = "GO_UPbast_16cNO_UHO_HO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(keggDOWNblast_16cNO_UHO_HO0.05, file = "keggDOWNblast_16cNO_UHO_HO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(keggUPbast_16cNO_UHO_HO0.05, file = "keggUPbast_16cNO_UHO_HO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(react_DOWNblast_16cNO_UHO_HO0.05, file = "react_DOWNblast_16cNO_UHO_HO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(react_UPbast_16cNO_UHO_HO0.05, file = "react_UPbast_16cNO_UHO_HO0.05no26.txt", sep = "\t", row.names = T, col.names = TRUE)

#ULTRAHYPOXIA

UPbast_16cUHO_HO_0.05 
DOWNblast_16cUHO_HO_0.05 

DOWNblast_16cUHO_HO_0.05G<- rownames(DOWNblast_16cUHO_HO_0.05 ) 
GO_DOWNblast_16cUHO_HO_0.05G <- enrichGO(gene = DOWNblast_16cUHO_HO_0.05G, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "BP")
GO_DOWNblast_16cUHO_HO_0.05G<-as.data.frame(GO_DOWNblast_16cUHO_HO_0.05G)

UPbast_16cUHO_HO_0.05G<- rownames(UPbast_16cUHO_HO_0.05) 
GO_UPbast_16cUHO_HO_0.05G <- enrichGO(gene = UPbast_16cUHO_HO_0.05G, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "BP")
GO_UPbast_16cUHO_HO_0.05G<-as.data.frame(GO_UPbast_16cUHO_HO_0.05G)

entrazDOWNblast_16cUHO_HO_0.05G<- mapIds(org.Bt.eg.db, keys = DOWNblast_16cUHO_HO_0.05G, column = "ENTREZID", keytype = "SYMBOL")
keggDOWNblast_16cUHO_HO_0.05G<- enrichKEGG(gene=entrazDOWNblast_16cUHO_HO_0.05G, organism = "bta")
keggDOWNblast_16cUHO_HO_0.05G <- as.data.frame(keggDOWNblast_16cUHO_HO_0.05G)

entrazUPbast_16cUHO_HO_0.05G<- mapIds(org.Bt.eg.db, keys = UPbast_16cUHO_HO_0.05G, column = "ENTREZID", keytype = "SYMBOL")
keggUPbast_16cUHO_HO_0.05G<- enrichKEGG(gene=entrazUPbast_16cUHO_HO_0.05G, organism = "bta")
keggUPbast_16cUHO_HO_0.05G <- as.data.frame(keggUPbast_16cUHO_HO_0.05G)

react_DOWNblast_16cUHO_HO_0.05G<- enrichPathway(gene=entrazDOWNblast_16cUHO_HO_0.05G, pvalueCutoff = 0.05, readable=TRUE, organism = "bovine" )
react_DOWNblast_16cUHO_HO_0.05G<- as.data.frame(react_DOWNblast_16cUHO_HO_0.05G)

react_UPbast_16cUHO_HO_0.05G<- enrichPathway(gene=entrazUPbast_16cUHO_HO_0.05G, pvalueCutoff = 0.05, readable=TRUE, organism = "bovine" )
react_UPbast_16cUHO_HO_0.05G<- as.data.frame(react_UPbast_16cUHO_HO_0.05G)

write.table(GO_DOWNblast_16cUHO_HO_0.05G, file = "GO_DOWNblast_16cUHO_HO_0.05Gno26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(GO_UPbast_16cUHO_HO_0.05G, file = "GO_UPbast_16cUHO_HO_0.05Gno26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(keggDOWNblast_16cUHO_HO_0.05G, file = "keggDOWNblast_16cUHO_HO_0.05G.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(keggUPbast_16cUHO_HO_0.05G, file = "keggUPbast_16cUHO_HO_0.05Gno26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(react_DOWNblast_16cUHO_HO_0.05G, file = "react_DOWNblast_16cUHO_HO_0.05Gno26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(react_UPbast_16cUHO_HO_0.05G, file = "react_UPbast_16cUHO_HO_0.05Gno26.txt", sep = "\t", row.names = T, col.names = TRUE)

#HYPOXIA

DOWNblast_16chypUHO0.05G<- rownames(DOWNblast_16chypUHO0.05) 
GO_DOWNblast_16chypUHO0.05G<- enrichGO(gene = DOWNblast_16chypUHO0.05G, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "BP")
GO_DOWNblast_16chypUHO0.05G<-as.data.frame(GO_DOWNblast_16chypUHO0.05G)

UPbast_16chypUHO0.05G <- rownames(UPbast_16chypUHO0.05) 
GO_UPbast_16chypUHO0.05G <- enrichGO(gene = UPbast_16chypUHO0.05G, OrgDb = "org.Bt.eg.db", keyType = "SYMBOL", ont = "BP")
GO_UPbast_16chypUHO0.05G<-as.data.frame(GO_UPbast_16chypUHO0.05G)

entrazDOWNblast_16chypUHO0.05G<- mapIds(org.Bt.eg.db, keys = DOWNblast_16chypUHO0.05G, column = "ENTREZID", keytype = "SYMBOL")
keggDOWNblast_16chypUHO0.05G<- enrichKEGG(gene=entrazDOWNblast_16chypUHO0.05G, organism = "bta")
keggDOWNblast_16chypUHO0.05G <- as.data.frame(keggDOWNblast_16chypUHO0.05G)

entrazUPbast_16chypUHO0.05G<- mapIds(org.Bt.eg.db, keys = UPbast_16chypUHO0.05G, column = "ENTREZID", keytype = "SYMBOL")
keggUPbast_16chypUHO0.05G<- enrichKEGG(gene=entrazUPbast_16chypUHO0.05G, organism = "bta")
keggUPbast_16chypUHO0.05G <- as.data.frame(keggUPbast_16chypUHO0.05G)

react_DOWNblast_16chypUHO0.05G<- enrichPathway(gene=entrazDOWNblast_16chypUHO0.05G, pvalueCutoff = 0.05, readable=TRUE, organism = "bovine" )
react_DOWNblast_16chypUHO0.05G<- as.data.frame(react_DOWNblast_16chypUHO0.05G)

react_UPbast_16chypUHO0.05G<- enrichPathway(gene=entrazUPbast_16chypUHO0.05G, pvalueCutoff = 0.05, readable=TRUE, organism = "bovine" )
react_UPbast_16chypUHO0.05G<- as.data.frame(react_UPbast_16chypUHO0.05G)

write.table(GO_DOWNblast_16chypUHO0.05G, file = "GO_DOWNblast_16chypUHO0.05Gno26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(GO_UPbast_16chypUHO0.05G, file = "GO_UPbast_16chypUHO0.05Gno26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(keggDOWNblast_16chypUHO0.05G, file = "keggDOWNblast_16chypUHO0.05Gno26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(keggUPbast_16chypUHO0.05G, file = "keggUPbast_16chypUHO0.05Gno26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(react_DOWNblast_16chypUHO0.05G, file = "react_DOWNblast_16chypUHO0.05Gno26.txt", sep = "\t", row.names = T, col.names = TRUE)
write.table(react_UPbast_16chypUHO0.05G, file = "react_UPbast_16chypUHO0.05Gno26.txt", sep = "\t", row.names = T, col.names = TRUE)

```
#VISUAL PRESENTATION

```{r}


GO_UP16c_hyp<-read.table("gprofilernew.txt", header = TRUE, sep = "\t", fill = TRUE)

hyp16UP <- ggplot(GO_UP16c_hyp, aes(x=Gene, y=GO_Tterm)) +
  geom_bar(stat="identity", fill="#DEDBEE") +
  labs(x="Gene", y="") +
  theme_minimal()+
  theme(axis.text.x = element_text(size=rel(2)),
        axis.title = element_text(size=rel(2)),
        axis.text.y = element_text(size=rel(2)))+
   xlim(0, 180)

ggsave(hyp16UP, filename= "hyp16UP_GOno26.svg", width = 20, height = 10)


GO_UP16c_norm<-read.table("GO_UP16c_norm.txt", header = TRUE, sep = "\t", fill = TRUE)

norm16UP <- ggplot(GO_UP16c_norm, aes(x=Count, y=GO_term)) +
  geom_bar(stat="identity", fill="#F4E6AA") +
  labs(x="Gene", y="") +
  theme_minimal()+
  theme(axis.text.x = element_text(size=rel(2)),
        axis.title = element_text(size=rel(2)),
        axis.text.y = element_text(size=rel(2)))+
  xlim(0, 170)

ggsave(norm16UP, filename= "norm16UP_GO.svg", height = 8, width = 10)

kegg_DOWN16c_hyponly<-read.table("keggDOWN16c_HO_onlyno26.txt", header = TRUE, sep = "\t", fill = TRUE)
hyp16down <- ggplot(kegg_DOWN16c_hyponly, aes(x=Count, y=Description)) +
  geom_bar(stat="identity", fill="#DEDBEE") +
  labs(x="Gene", y="") +
  theme_minimal()+
  theme(axis.text.x = element_text(size=rel(2)),
        axis.title = element_text(size=rel(2)),
        axis.text.y = element_text(size=rel(2)))
ggsave(hyp16down, filename= "hyp16down.svg", height = 8, width = 10)

kegg_DOWN16c_normonly<-read.table("keggDOWN16c_noonlyno26.txt", header = TRUE, sep = "\t", fill = TRUE)
norm16down <- ggplot(kegg_DOWN16c_normonly, aes(x=Count, y=Description)) +
  geom_bar(stat="identity", fill="#F4E6AA") +
  labs(x="Gene", y="") +
  theme_minimal()+
  theme(axis.text.x = element_text(size=rel(2)),
        axis.title = element_text(size=rel(2)),
        axis.text.y = element_text(size=rel(2)))
ggsave(norm16down, filename= "norm16down.svg", height = 8, width = 10)
                    
```

```{r}
library(dplyr)

merged_df <- keggDOWN16c_normUHO_HO0.05 %>%
  left_join(keggDOWN16c_hypUHO0.05, by = "Description") 

write.table(merged_df, file = "commonKEGGdown16c NO AND HO.txt", sep = "\t", row.names = T, col.names = TRUE)

#kegg topp 40 for normoxia and hypoxia

top40_DOWN16C_norm<- keggDOWN16c_normUHO_HO0.05[1:40,]
top40_DOWN16C_hyp<- keggDOWN16c_hypUHO0.05[1:40,]

calculate_ratio <- function(gene_ratio) {
  parts <- strsplit(gene_ratio, "/")[[1]]
  numerator <- as.numeric(parts[1])
  denominator <- as.numeric(parts[2])
  return(numerator / denominator)
}

top40_DOWN16C_hyp <- top40_DOWN16C_hyp %>%
  mutate(ratio = sapply(GeneRatio, calculate_ratio))


mypalette <- brewer.pal(3, "YlOrRd")

keggDOWN16CHYP<- ggplot(top40_DOWN16C_hyp)+
  geom_point(aes(x = Count, y = Description, color = -log10(p.adjust)), 
             size = 2) +
  theme_bw() +
  theme(axis.text.x = element_text(size=rel(1.15)),
        axis.title = element_text(size=rel(1.15))) +
  xlab("Gene count") +
  ylab("KEGG pathways") +
  ggtitle("Top 40 downregulated KEGG pathways at 16C in hypoxia") +
  theme(plot.title = element_text(hjust=0.5, 
  	face = "bold")) +
  scale_color_gradientn(name = "Significance \n (-log10(padj))", colors = mypalette ) +
  theme(legend.title = element_text(size=rel(1.15),
	hjust=0.5, 
	face="bold")) +
    xlim(0, 170)
ggsave(keggDOWN16CHYP, filename="keggDOWN16CHYP.pdf", height = 10, width = 10)

keggDOWN16Cnorm<- ggplot(top40_DOWN16C_norm)+
  geom_point(aes(x = Count, y = Description, color = -log10(p.adjust)), 
             size = 2) +
  theme_bw() +
  theme(axis.text.x = element_text(size=rel(1.15)),
        axis.title = element_text(size=rel(1.15))) +
  xlab("Gene count") +
  ylab("KEGG pathways") +
  ggtitle("Top 40 downregulated KEGG pathways at 16C in normoxia") +
  theme(plot.title = element_text(hjust=0.5, 
  	face = "bold")) +
  scale_color_gradientn(name = "Significance \n (-log10(padj))", colors = mypalette ) +
  theme(legend.title = element_text(size=rel(1.15),
	hjust=0.5, 
	face="bold")) +
    xlim(0, 130)
ggsave(keggDOWN16Cnorm, filename="keggDOWN16Cnorm.pdf", height = 10, width = 10)



# Create data frame
figure5data <- data.frame(
  Group = factor(rep(c("normoxia", "hypoxia", "ultrahypoxia"), each=2)),
  Type = rep(c("Positive", "Negative"), 3),
  Value = c(695, -533, 2006, -227, 1956, -1356))

colourFig5<- c("normoxia" = "#F4E6AA", "hypoxia" = "#DEDBEE", "ultrahypoxia" = "#C8DBC8")

# Create basic bar plot
figure5b<- ggplot(figure5data,aes(x=Group, y=Value, fill=Type)) +
  geom_bar(stat="identity") +
  geom_hline(yintercept=0, color="black") +
  theme_minimal() +
  labs(y="Number of DEG blastocyst vs 16C", x="Condition") +
  geom_text(aes(label=Value), position=position_dodge(width=0.9), vjust=-0.3)

ggsave(figure5b, filename="DEGblast_16C.pdf", height = 10, width = 10)
ggsave(figure5b, filename="DEGblast_16C.svg", height = 10, width = 10)
```

```{r}
keggUPbast_16chypUHO0.05G$Condition<- "hypoxia"
keggUPbast_16cNO_UHO_HO0.05$Condition<- "normoxia"
keggUPbast_16cUHO_HO_0.05G$Condition<- "ultrahypoxia"

figure5ccomb<- rbind(keggUPbast_16chypUHO0.05G, keggUPbast_16cNO_UHO_HO0.05, keggUPbast_16cUHO_HO_0.05G)

shared <- intersect(keggUPbast_16chypUHO0.05G$Description, keggUPbast_16cUHO_HO_0.05G$Description)
unique_HO <- setdiff(keggUPbast_16chypUHO0.05G$Description, keggUPbast_16cUHO_HO_0.05G$Description)
unique_UHO <- setdiff(keggUPbast_16cUHO_HO_0.05G$Description, keggUPbast_16chypUHO0.05G$Description)

df_combHO_UHO <- data.frame(
  Description = c(shared, unique_HO, unique_UHO),
  Condition = c(rep("hypoxia/ultrahypoxia", length(shared)), rep("hypoxia", length(unique_HO)), rep("ultrahypoxia", length(unique_UHO)))
)

write.table(df_combHO_UHO, file = "KEGG_UP_HO_UHO_blastvs16c.txt", sep = "\t", row.names = T, col.names = TRUE)

df_combHO_UHO<- read.table("KEGG_UP_HO_UHO_blastvs16c.txt", header = TRUE, sep = "\t", fill = TRUE)

library(circlize)
chordDiagram(df_combHO_UHO, grid.col = colourFig5, transparency = 0.5, annotationTrack = "grid", preAllocateTracks = 1) 


```

```{r}

shared_all <- Reduce(intersect, list(keggUPbast_16chypUHO0.05G$Description, keggUPbast_16cUHO_HO_0.05G$Description, keggUPbast_16cNO_UHO_HO0.05$Description ))
shared_HO_UHO <- setdiff(intersect(keggUPbast_16chypUHO0.05G$Description, keggUPbast_16cUHO_HO_0.05G$Description), shared_all)
unique_HO <- setdiff(keggUPbast_16chypUHO0.05G$Description, union(keggUPbast_16cUHO_HO_0.05G$Description, keggUPbast_16cNO_UHO_HO0.05$Description))
unique_UHO <- setdiff(keggUPbast_16cUHO_HO_0.05G$Description, union(keggUPbast_16chypUHO0.05G$Description, keggUPbast_16cNO_UHO_HO0.05$Description))
unique_NO <- setdiff(keggUPbast_16cNO_UHO_HO0.05$Description, union(keggUPbast_16chypUHO0.05G$Description, keggUPbast_16cUHO_HO_0.05G$Description))

num_sectors <- length(unique(c(df_combined_allUPkeggblast$Description, df_combined_allUPkeggblast$Condition)))

gap_degrees <- rep(1, num_sectors)

# Create the new data frame
df_combined_allUPkeggblast <- data.frame(
  Description = c(shared_all, shared_HO_UHO, unique_HO, unique_UHO, unique_NO),
  Condition = c(rep("Shared_All", length(shared_all)), 
                rep("HO/UHO", length(shared_HO_UHO)), 
                rep("HO", length(unique_HO)), 
                rep("UHO", length(unique_UHO)), 
                rep("NO", length(unique_NO)))
)

rownames(df_combined_allUPkeggblast)<- df_combined_allUPkeggblast$Description

library(circlize)
circos.clear()

chordDiagram(df_combined_allUPkeggblast, grid.col = colourFig5, annotationTrack = "grid", 
         preAllocateTracks = list(track.height = 0.3))


write.table(df_combined_allUPkeggblast, file = "df_combined_allUPkeggblastno26.txt", sep = "\t", row.names = T, col.names = TRUE)
library(svglite)

svglite("chord_diagram.svg", width = 10, height = 10)
chordDiagram(df_combined_allUPkeggblast, grid.col = colourFig5, annotationTrack = "grid", 
         preAllocateTracks = list(track.height = 0.3))
dev.off()


```

